# Can multi-stakeholder agents evaluate a therapeutic asset?

## TRANSEURO Case: Agentic vs. Single-LLM Evidence Synthesis

**Research question:** Does agentic reasoning (independent tool-calling, iterative
retrieval) produce more thorough, better-grounded therapeutic risk assessments
than a single-call LLM reading a fixed evidence snapshot?

**Case:** TRANSEURO (NCT01898390), a redesigned fetal ventral mesencephalic
tissue transplant trial for Parkinson's disease. Decision point: **December 31,
2014**, just before grafting began (2015-2018), assessing whether the
redesign adequately addressed graft-induced dyskinesia (GID), the central
risk identified in earlier NIH-funded trials (Freed 2001, Olanow 2003).

This case was chosen deliberately as a **contamination-failed** case (see
project-wide contamination protocol): the model already has confident
recall of TRANSEURO's actual outcome, so this case is evaluated on
**reasoning quality** (citation fidelity, evidence grounding, calibration),
not outcome prediction.

## Corpus construction
- Three independently pre-specified PubMed queries ("angles"): program-specific
  (TRANSEURO/Barker), disease-modality general (fetal VM transplantation,
  1970-2014), and field-mechanism (graft-induced dyskinesia, 1990-2014)
- Date cutoff enforced **twice**: at query time (`[pdat]` filter) and again
  by re-checking each result's actual `pubdate` — the query-time filter alone
  let two post-cutoff papers through during testing
- Selection: union of top-10 by relevance rank and top-10 by citation count
  per angle (relevance alone buries older foundational papers; citation
  count alone under-weights recent ones)
- Access checked via PMC and Unpaywall; abstract-only where no open full
  text exists (logged explicitly, not silently substituted)
- No manual paper curation — automated, reproducible queries only, to avoid
  hindsight bias in evidence selection

## Four-condition design

The code and result filenames below use `week1`-`week4`, reflecting the order these
conditions were actually built in. The write-up and graphics use plainer labels for
the same conditions, mapped here so the two are easy to cross-reference:

| Code label | Personas | Evidence | Tool calls | Called in the write-up |
|---|---|---|---|---|
| `week1` | Single call, 4 sections | Frozen corpus | None | *(persona-separation check only, not featured in the write-up)* |
| `week2` | 4 independent calls | Frozen corpus | None | "No search" |
| `week3` | 4 independent calls | Frozen corpus | Capped at 1 round | "One search" |
| `week4` | 4 independent calls | Frozen corpus | Unlimited rounds | "Repeated / agentic search" |

Week 3→4 is the core "agentic vs. not" comparison; Week 1→2 tests whether
persona separation alone changes output, independent of tool access.

**Personas:** Biology, Clinical, Regulatory, CMC/Manufacturing (Commercial
dropped — TRANSEURO is an academic/EU-funded consortium trial, not a
commercially sponsored program).

## Setup

This notebook needs a `.env` file in the same directory, containing:

```
ANTHROPIC_API_KEY=your_key_here
NCBI_API_KEY=your_ncbi_key_here
NCBI_EMAIL=your_email@example.com
```

`ANTHROPIC_API_KEY` is required for the Week 1-4 persona calls. `NCBI_API_KEY` is optional but recommended (raises the PubMed rate limit from 3 to 10 requests/second, register free at https://www.ncbi.nlm.nih.gov/account/). `NCBI_EMAIL` is NCBI's requested etiquette identifier for API requests, not a credential.

Dependencies: `pip install requests pandas anthropic python-dotenv`

In [ ]:
import requests
import time
import xml.etree.ElementTree as ET
import pandas as pd
import os
from anthropic import Anthropic
from dotenv import load_dotenv

load_dotenv()  # reads ANTHROPIC_API_KEY, NCBI_API_KEY, NCBI_EMAIL from a local .env file

EUTILS_BASE = "https://eutils.ncbi.nlm.nih.gov/entrez/eutils"

# Optional but recommended: register a free NCBI API key to raise the rate
# limit from 3 to 10 requests/second: https://www.ncbi.nlm.nih.gov/account/
NCBI_API_KEY = os.getenv("NCBI_API_KEY")  # set in your own .env file, or leave unset

# NCBI etiquette: identify yourself in requests
TOOL_NAME = "transeuro-corpus-poc"
EMAIL = os.getenv("NCBI_EMAIL", "your_email@example.com")  # set your own in .env

In [7]:
pd.set_option("display.max_colwidth", None)

## Pipeline for building PubMed corpus


esearch → esummary → enforce_date_cutoff →  pubtype classification → PMC check →  DOI fetch  → Unpaywall check →  citation counts fetch → select_by_either_metric → corpus: combine selected papers & remove duplicates → fetch abstracts for corpus papers

In [17]:
def esearch(query: str, retmax: int = 200, sort: str = "relevance") -> dict:
    """Run a PubMed search and return the raw esearch response (JSON).
    retmax is set high here (200) so we can inspect the full relevance
    distribution before deciding a cutoff, not to imply we'll use all 200.
    """
    params = {
        "db": "pubmed",
        "term": query,
        "retmode": "json",
        "retmax": retmax,
        "sort": sort,
        "tool": TOOL_NAME,
        "email": EMAIL,
    }
    if NCBI_API_KEY:
        params["api_key"] = NCBI_API_KEY
    resp = requests.get(f"{EUTILS_BASE}/esearch.fcgi", params=params, timeout=15)
    resp.raise_for_status()
    return resp.json()


def esummary(pmids: list) -> pd.DataFrame:
    """Fetch title, journal, publication date, and publication type(s) for PMIDs."""
    if not pmids:
        return pd.DataFrame(columns=["pmid", "title", "journal", "pubdate", "pubtypes"])
    params = {
        "db": "pubmed",
        "id": ",".join(pmids),
        "retmode": "json",
        "tool": TOOL_NAME,
        "email": EMAIL,
    }
    if NCBI_API_KEY:
        params["api_key"] = NCBI_API_KEY
    resp = requests.get(f"{EUTILS_BASE}/esummary.fcgi", params=params, timeout=15)
    resp.raise_for_status()
    data = resp.json()["result"]
    rows = []
    for pmid in data.get("uids", []):
        rec = data[pmid]
        rows.append({
            "pmid": pmid,
            "title": rec.get("title", ""),
            "journal": rec.get("fulljournalname", ""),
            "pubdate": rec.get("pubdate", ""),
            "pubtypes": rec.get("pubtype", []),  # e.g. ["Journal Article", "Review"]
        })
    return pd.DataFrame(rows)

In [18]:
def enforce_date_cutoff(df: pd.DataFrame, cutoff_year: int = 2014) -> pd.DataFrame:
    """Strictly re-filter on the actual pubdate field, never trust PubMed's
    server-side date filter alone for something this important."""
    df = df.copy()
    df["pub_year"] = df["pubdate"].str.extract(r"(\d{4})").astype(float)
    before = len(df)
    df = df[df["pub_year"] <= cutoff_year].reset_index(drop=True)
    dropped = before - len(df)
    if dropped > 0:
        print(f"Dropped {dropped} paper(s) with pub_year > {cutoff_year}, "
              f"despite passing the API's own date filter.")
    return df

In [19]:
def check_pmc_fulltext(pmid: str) -> str | None:
    """Return the PMCID (e.g. 'PMC1234567') if this PMID has a PMC full-text
    record, otherwise None. Uses XML retmode, elink's native format."""
    params = {
        "dbfrom": "pubmed",
        "db": "pmc",
        "id": pmid,
        "linkname": "pubmed_pmc",
        "tool": TOOL_NAME,
        "email": EMAIL,
    }
    if NCBI_API_KEY:
        params["api_key"] = NCBI_API_KEY
    resp = requests.get(f"{EUTILS_BASE}/elink.fcgi", params=params, timeout=15)
    resp.raise_for_status()

    try:
        root = ET.fromstring(resp.content)
    except ET.ParseError as e:
        print(f"XML parse error for PMID {pmid}: {e}")
        print(resp.text[:300])
        return None

    for linksetdb in root.findall(".//LinkSetDb"):
        if linksetdb.findtext("LinkName") == "pubmed_pmc":
            id_elem = linksetdb.find("Link/Id")
            if id_elem is not None:
                return f"PMC{id_elem.text}"
    return None

In [20]:
def fetch_dois(pmids: list) -> dict:
    """Return a dict mapping pmid -> DOI (or None if not found)."""
    if not pmids:
        return {}
    params = {
        "db": "pubmed",
        "id": ",".join(pmids),
        "retmode": "json",
        "tool": TOOL_NAME,
        "email": EMAIL,
    }
    if NCBI_API_KEY:
        params["api_key"] = NCBI_API_KEY
    resp = requests.get(f"{EUTILS_BASE}/esummary.fcgi", params=params, timeout=15)
    resp.raise_for_status()
    data = resp.json()["result"]
    dois = {}
    for pmid in data.get("uids", []):
        rec = data[pmid]
        doi = next((a["value"] for a in rec.get("articleids", []) if a.get("idtype") == "doi"), None)
        dois[pmid] = doi
    return dois

In [21]:
def check_unpaywall(doi: str) -> dict:
    """Query Unpaywall for open-access status and the best available URL."""
    if not doi:
        return {"is_oa": False, "oa_url": None}
    resp = requests.get(f"https://api.unpaywall.org/v2/{doi}", params={"email": EMAIL}, timeout=15)
    if resp.status_code == 404:
        return {"is_oa": False, "oa_url": None}  # DOI not in Unpaywall's database
    resp.raise_for_status()
    data = resp.json()
    best_oa = data.get("best_oa_location") or {}
    return {"is_oa": data.get("is_oa", False), "oa_url": best_oa.get("url")}

In [22]:
def fetch_citation_count(doi: str) -> int | None:
    """Query Semantic Scholar for a paper's citation count, by DOI."""
    if not doi:
        return None
    url = f"https://api.semanticscholar.org/graph/v1/paper/DOI:{doi}"
    resp = requests.get(url, params={"fields": "citationCount"}, timeout=15)
    if resp.status_code == 404:
        return None
    resp.raise_for_status()
    return resp.json().get("citationCount")

In [23]:
def select_by_either_metric(df: pd.DataFrame, relevance_col="rank", citation_col="citation_count", top_n=20):
    """Select papers ranking in the top N by *either* relevance or citation
    count, not the sum of both lists.

    Relevance rank favors recency and dense term-matching to the query, and
    can bury older, foundational papers (e.g. a landmark 2003 trial ranked
    82nd out of 288 by PubMed's relevance sort). Citation count favors
    field-wide importance instead, but is biased toward older papers, since
    citations accumulate over time. Selecting on either metric lets a paper
    qualify by being highly relevant to this specific query OR structurally
    important to the field, without requiring both.

    Papers ranking well on both metrics are only counted once (set union,
    not concatenation), so the result size is <= 2 * top_n, and will be
    smaller wherever the two rankings overlap. Papers with a missing
    citation count (not found in Semantic Scholar) cannot qualify via the
    citation path, only via relevance.
    """
    top_by_relevance = set(df.nsmallest(top_n, relevance_col)["pmid"])
    top_by_citations = set(df.nlargest(top_n, citation_col, keep="all")["pmid"])
    selected_pmids = top_by_relevance | top_by_citations
    return df[df["pmid"].isin(selected_pmids)].reset_index(drop=True)

In [24]:
def fetch_abstracts(pmids: list) -> dict:
    """Return a dict mapping pmid -> abstract text (or empty string if unavailable)."""
    if not pmids:
        return {}
    params = {
        "db": "pubmed",
        "id": ",".join(pmids),
        "rettype": "abstract",
        "retmode": "xml",
        "tool": TOOL_NAME,
        "email": EMAIL,
    }
    if NCBI_API_KEY:
        params["api_key"] = NCBI_API_KEY
    resp = requests.get(f"{EUTILS_BASE}/efetch.fcgi", params=params, timeout=15)
    resp.raise_for_status()
    root = ET.fromstring(resp.content)

    abstracts = {}
    for article in root.findall(".//PubmedArticle"):
        pmid_elem = article.find(".//PMID")
        pmid = pmid_elem.text if pmid_elem is not None else None
        abstract_parts = article.findall(".//AbstractText")
        text = " ".join(part.text or "" for part in abstract_parts)
        if pmid:
            abstracts[pmid] = text
    return abstracts

In [25]:
NON_PRIMARY_TYPES = {
    "Review", "Comment", "Editorial", "Letter",
    "Historical Article", "Biography", "Practice Guideline", "Congresses"
}

## Step 1: Define the queries

In [42]:
#Program-specific query
angle1_query = (
    '(TRANSEURO[tiab] OR "trans-euro"[tiab] OR '
    '("Barker RA"[Author] AND ("Parkinson Disease"[MeSH] OR Parkinson*[tiab]) '
    'AND (transplant*[tiab] OR graft*[tiab] OR "cell therapy"[tiab]))) '
    'AND ("1990/01/01"[Date - Publication] : "2014/12/31"[Date - Publication]) '
    'NOT xenotransplant*[tiab] NOT xenograft*[tiab]'
)

In [43]:
# Non-program specific (but same disease & modality) query
angle2_query = (
    '("fetal ventral mesencephalic"[tiab] OR "fetal nigral"[tiab] OR '
    '"fetal mesencephalic"[tiab] OR "fetal cell transplantation"[tiab] OR '
    '"embryonic dopamine neuron*"[tiab])'
    'AND ("Parkinson Disease"[MeSH] OR Parkinson*[tiab]) '
    'AND ("1970/01/01"[Date - Publication] : "2014/12/31"[Date - Publication])'
)

In [44]:
# Field-level mechanism, graft-induced dyskinesia
angle3_query = (
    '("graft-induced dyskinesia"[tiab] OR "graft induced dyskinesia"[tiab])'
    'AND (Parkinson*[tiab] OR transplant*[tiab])'
    'AND ("1990/01/01"[Date - Publication] : "2014/12/31"[Date - Publication])'
)

## Step 2: Run each query through the pipeline

### Angle1_query : program-specific

#### Searching articles

In [45]:
search_result = esearch(angle1_query, retmax=200)
pmids = search_result["esearchresult"]["idlist"]
print(f"Total hits after exclusion: {search_result['esearchresult']['count']}")

df = esummary(pmids)
df["rank"] = range(1, len(df) + 1)

df = enforce_date_cutoff(df, cutoff_year=2014)

Total hits after exclusion: 42

#### Pubtype classification

In [46]:
is_review = df["pubtypes"].apply(lambda types: bool(set(types) & NON_PRIMARY_TYPES))
reviews_df = df[is_review].reset_index(drop=True)
primary_df = df[~is_review].reset_index(drop=True)

print(f"Reviews: {len(reviews_df)}")
print(f"Primary literature: {len(primary_df)}")

Reviews: 25
Primary literature: 17

In [47]:
print("=== Primary literature ===")
for _, row in primary_df.iterrows():
    print(f"{row['rank']}. {row['title']} ({row['pubdate']})")

print("\n=== Reviews ===")
for _, row in reviews_df.iterrows():
    print(f"{row['rank']}. {row['title']} ({row['pubdate']})")

=== Primary literature ===
9. Which patients with Parkinson's disease participate in clinical trials? One centre's experiences with a new cell based therapy trial (TRANSEURO). (2014)
17. Animal models of neurodegenerative diseases. (2009)
27. Graft-induced dyskinesias in Parkinson's disease: what is it all about? (2010 Aug 6)
28. Anti-amyloid compounds inhibit α-synuclein aggregation induced by protein misfolding cyclic amplification (PMCA). (2014 Apr 25)
29. Transplantation of human fetal tissue for neurodegenerative diseases: validation of a new protocol for microbiological analysis and bacterial decontamination. (2014)
30. Developing stem cell therapies for Parkinson's disease: waiting until the time is right. (2014 Nov 6)
31. Modelling of a targeted nanotherapeutic 'stroma' to deliver the cytokine LIF, or XAV939, a potent inhibitor of Wnt-β-catenin signalling, for use in human fetal dopaminergic grafts in Parkinson's disease. (2014 Oct)
33. The role of anxiety in the development of levodopa-induced dyskinesias in an animal model of Parkinson's disease, and the effect of chronic treatment with the selective serotonin reuptake inhibitor citalopram. (2008 Apr)
34. Efficient expansion and dopaminergic differentiation of human fetal ventral midbrain neural stem cells by midbrain morphogens. (2013 Jan)
35. Transplantation of expanded neural precursor cells from the developing pig ventral mesencephalon in a rat model of Parkinson's disease. (2003 Jul)
36. The effect of truncated human alpha-synuclein (1-120) on dopaminergic cells in a transgenic mouse model of Parkinson's disease. (2007)
37. Transplanted human neural precursor cells migrate widely but show no lesion-specific tropism in the 6-hydroxydopamine rat model of Parkinson's disease. (2006)
38. Staging and preparation of human fetal striatal tissue for neural transplantation in Huntington's disease. (2003)
39. Dopaminergic neuronal survival and the effects of bFGF in explant, three dimensional and monolayer cultures of embryonic rat ventral mesencephalon. (1995)
40. Neural transplantation therapies for Parkinson's and Huntington's diseases. (2001 Jun 1)
41. A comparative study of preparation techniques for improving the viability of nigral grafts using vital stains, in vitro cultures, and in vivo grafts. (1995 Mar-Apr)
42. The importance of A9 dopaminergic neurons in mediating the functional benefits of fetal ventral mesencephalon transplants and levodopa-induced dyskinesias. (2007 Mar)

=== Reviews ===
1. Cell-based therapies for Parkinson's disease. (2011 Jun)
2. Cell transplantation in Parkinson's disease: problems and perspectives. (2010 Aug)
3. Stem cells and the treatment of Parkinson's disease. (2014 Oct)
4. Cell replacement therapy for Parkinson's disease. (2009 Jul)
5. Stem cells and regenerative therapies for Parkinson's disease. (2012)
6. Neural grafting in Parkinson's disease Problems and possibilities. (2010)
7. Stem cell therapies for Parkinson's disease: are trials just around the corner? (2014)
8. The future of cell therapies in the treatment of Parkinson's disease. (2007 Oct)
10. The future of cell therapies and brain repair: Parkinson's disease leads the way. (2014 Feb)
11. Is there a future for neural transplantation? (2004)
12. Immune problems in central nervous system cell therapy. (2004 Oct)
13. Treating Parkinson's disease in the 21st century: can stem cell transplantation compete? (2014 Aug 15)
14. The cellular repair of the brain in Parkinson's disease--past, present and future. (2004 Apr)
15. The search for a curative cell therapy in Parkinson's disease. (2008 Feb 15)
16. Current status of clinical trials of neural transplantation in Parkinson's disease. (2012)
18. Fetal dopaminergic transplantation trials and the future of neural grafting in Parkinson's disease. (2013 Jan)
19. Scientific and ethical issues related to stem cell research and interventions in neurodegenerative disorders of the brain. (2013 Nov)
20. Cell therapies for neurological disease--from bench to clinic to bench. (2005 Mar)
21. The future of cell-based transplantation therapies for neurodegenerative disorders. (2003 Dec)
22. The glial response to intracerebrally delivered therapies for neurodegenerative disorders: is this a critical issue? (2014)
23. Prospects for the treatment of Parkinson's disease using neural grafts. (2000 Jul)
24. New therapeutic approaches to Parkinson's disease including neural transplants. (2005 Sep)
25. The time course of loss of dopaminergic neurons and the gliotic reaction surrounding grafts of embryonic mesencephalon to the striatum. (1996 Sep)
26. Stem cells and neurodegenerative diseases: where is it all going? (2012 Nov)
32. Functional integration of neural grafts in Parkinson's disease. (1999 Dec)

Checking if Olanow's paper ("A double-blind controlled trial of bilateral fetal nigral transplantation in Parkinson's disease") is included

In [48]:
df[df["pmid"].str.contains("12953276", case=False, na=False)]

Empty DataFrame
Columns: [pmid, title, journal, pubdate, pubtypes, rank, pub_year]
Index: []

#### Checking PMC full-text availability

In [49]:
pmcids = []
for pmid in df["pmid"]:
    try:
        pmcids.append(check_pmc_fulltext(pmid))
    except Exception as e:
        print(f"Error checking PMID {pmid}: {e}")
        pmcids.append(None)
    time.sleep(0.4 if not NCBI_API_KEY else 0.15)

df["pmcid"] = pmcids
df["has_pmc_fulltext"] = df["pmcid"].notna()
print(f"{df['has_pmc_fulltext'].sum()} of {len(df)} papers have PMC full text")

6 of 42 papers have PMC full text

#### Fetching DOIs

In [50]:
doi_map = fetch_dois(df["pmid"].tolist())
df["doi"] = df["pmid"].map(doi_map)
print(f"{df['doi'].notna().sum()} of {len(df)} papers have a DOI on record")

42 of 42 papers have a DOI on record

#### Checking open acesss availability

In [51]:
oa_results = []
for doi in df["doi"]:
    try:
        oa_results.append(check_unpaywall(doi))
    except Exception as e:
        print(f"Error checking DOI {doi}: {e}")
        oa_results.append({"is_oa": False, "oa_url": None})
    time.sleep(0.2)

oa_df = pd.DataFrame(oa_results)
df["unpaywall_is_oa"] = oa_df["is_oa"]
df["unpaywall_url"] = oa_df["oa_url"]

df["has_any_legitimate_access"] = df["has_pmc_fulltext"] | df["unpaywall_is_oa"]
print(f"{df['has_any_legitimate_access'].sum()} of {len(df)} accessible via PMC or Unpaywall combined")

still_inaccessible = df[~df["has_any_legitimate_access"]]
print(f"\n{len(still_inaccessible)} still with no automated open route:")
for _, row in still_inaccessible.iterrows():
    print(f"- {row['title']} ({row['pubdate']})")

19 of 42 accessible via PMC or Unpaywall combined

23 still with no automated open route:
- Cell-based therapies for Parkinson's disease. (2011 Jun)
- Stem cells and the treatment of Parkinson's disease. (2014 Oct)
- Neural grafting in Parkinson's disease Problems and possibilities. (2010)
- Stem cell therapies for Parkinson's disease: are trials just around the corner? (2014)
- The future of cell therapies in the treatment of Parkinson's disease. (2007 Oct)
- Is there a future for neural transplantation? (2004)
- The cellular repair of the brain in Parkinson's disease--past, present and future. (2004 Apr)
- The search for a curative cell therapy in Parkinson's disease. (2008 Feb 15)
- Current status of clinical trials of neural transplantation in Parkinson's disease. (2012)
- Animal models of neurodegenerative diseases. (2009)
- Fetal dopaminergic transplantation trials and the future of neural grafting in Parkinson's disease. (2013 Jan)
- Scientific and ethical issues related to stem cell research and interventions in neurodegenerative disorders of the brain. (2013 Nov)
- The future of cell-based transplantation therapies for neurodegenerative disorders. (2003 Dec)
- Prospects for the treatment of Parkinson's disease using neural grafts. (2000 Jul)
- New therapeutic approaches to Parkinson's disease including neural transplants. (2005 Sep)
- The time course of loss of dopaminergic neurons and the gliotic reaction surrounding grafts of embryonic mesencephalon to the striatum. (1996 Sep)
- Stem cells and neurodegenerative diseases: where is it all going? (2012 Nov)
- Functional integration of neural grafts in Parkinson's disease. (1999 Dec)
- The role of anxiety in the development of levodopa-induced dyskinesias in an animal model of Parkinson's disease, and the effect of chronic treatment with the selective serotonin reuptake inhibitor citalopram. (2008 Apr)
- Transplantation of expanded neural precursor cells from the developing pig ventral mesencephalon in a rat model of Parkinson's disease. (2003 Jul)
- Transplanted human neural precursor cells migrate widely but show no lesion-specific tropism in the 6-hydroxydopamine rat model of Parkinson's disease. (2006)
- Dopaminergic neuronal survival and the effects of bFGF in explant, three dimensional and monolayer cultures of embryonic rat ventral mesencephalon. (1995)
- Neural transplantation therapies for Parkinson's and Huntington's diseases. (2001 Jun 1)

#### Fetching citation counts

In [52]:
citation_counts = []
for doi in df["doi"]:
    try:
        citation_counts.append(fetch_citation_count(doi))
    except Exception as e:
        print(f"Error fetching citation count for {doi}: {e}")
        citation_counts.append(None)
    time.sleep(1.0)  # Semantic Scholar's unauthenticated rate limit is stricter than NCBI's

df["citation_count"] = citation_counts
print(f"{df['citation_count'].notna().sum()} of {len(df)} papers have a citation count")

42 of 42 papers have a citation count

### Angle 2_query: non-program-specific

#### Searching papers

In [53]:
search_result = esearch(angle2_query, retmax=300)
print(f"Initial hits: {search_result['esearchresult']['count']}")

df2 = esummary(search_result["esearchresult"]["idlist"])
df2["rank"] = range(1, len(df2) + 1)

df2 = enforce_date_cutoff(df2, cutoff_year=2014)
print(f"Total hits after enforced date cutoff: {len(df2)}")

Initial hits: 290
Dropped 2 paper(s) with pub_year > 2014, despite passing the API's own date filter.
Total hits after enforced date cutoff: 288

In [54]:
df2[df2["pmid"].str.contains("12953276", case=False, na=False)]

,pmid,title,journal,pubdate,pubtypes,rank,pub_year
81,12953276,A double-blind controlled trial of bilateral fetal nigral transplantation in Parkinson's disease.,Annals of neurology,2003 Sep,"[Clinical Trial, Journal Article, Randomized Controlled Trial, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",82,2003.0

In [55]:
df2[df2["pmid"].str.contains("11236774", case=False, na=False)]

,pmid,title,journal,pubdate,pubtypes,rank,pub_year
52,11236774,Transplantation of embryonic dopamine neurons for severe Parkinson's disease.,The New England journal of medicine,2001 Mar 8,"[Clinical Trial, Journal Article, Randomized Controlled Trial, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",53,2001.0

#### Pubtype classification

In [56]:
is_review_2 = df2["pubtypes"].apply(lambda types: bool(set(types) & NON_PRIMARY_TYPES))
reviews_df_2  = df2[is_review_2].reset_index(drop=True)
primary_df_2  = df2[~is_review_2].reset_index(drop=True)

print(f"Reviews: {len(reviews_df_2)}")
print(f"Primary literature: {len(primary_df_2)}")

Reviews: 84
Primary literature: 204

In [57]:
print("=== Primary literature ===")
for _, row in primary_df_2.iterrows():
    print(f"{row['rank']}. {row['title']} ({row['pubdate']})")

print("\n=== Reviews ===")
for _, row in reviews_df_2.iterrows():
    print(f"{row['rank']}. {row['title']} ({row['pubdate']})")

=== Primary literature ===
47. Transplantation of fetal mesencephalic tissue in Parkinson's patients. (1994)
53. Transplantation of embryonic dopamine neurons for severe Parkinson's disease. (2001 Mar 8)
58. Ethical aspects of neural tissue transplantation. (1999 Sep)
63. Bilateral fetal nigral transplantation into the postcommissural putamen in Parkinson's disease. (1995 Sep)
68. Growth factors rescue embryonic dopamine neurons from programmed cell death. (1996 Jul)
70. Dopamine neuron stimulating actions of a GDNF propeptide. (2010 Mar 18)
71. Long-term evaluation of bilateral fetal nigral transplantation in Parkinson disease. (1999 Feb)
73. Dyskinesia after fetal cell transplantation for parkinsonism: a PET study. (2002 Nov)
76. Functional fetal nigral grafts in a patient with Parkinson's disease: chemoanatomic, ultrastructural, and metabolic studies. (1996 Jun 24)
78. Pallidal neuronal discharge in Parkinson's disease following intraputamenal fetal mesencephalic allograft. (2011 Mar)
81. Cryopreservation, culture, and transplantation of human fetal mesencephalic tissue into monkeys. (1988 Nov 4)
82. A double-blind controlled trial of bilateral fetal nigral transplantation in Parkinson's disease. (2003 Sep)
83. Clonal human fetal ventral mesencephalic dopaminergic neuron precursors for cell therapy research. (2012)
84. Neural transplantation cannula and microinjector system: experimental and clinical experience. Technical note. (2000 Mar)
86. Serotonin neuron loss and nonmotor symptoms continue in Parkinson's patients treated with dopamine grafts. (2012 Apr 4)
87. Clinical study of fetal mesencephalic intracerebral transplants for the treatment of Parkinson's disease. (1996 Mar-Apr)
90. Long-term clinical outcome of fetal cell transplantation for Parkinson disease: two case reports. (2014 Jan)
91. Homogenous fetal dopaminergic cell transplantation in rat striatum by cell suspension methods. (1993 Jun)
92. Intranigral fetal dopamine grafts induce behavioral compensation in the rat Parkinson model. (1994 Jun)
93. Fetal nigral grafts survive and mediate clinical benefit in a patient with Parkinson's disease. (1998 May)
95. Embryonic ventral mesencephalic grafts improve levodopa-induced dyskinesia in a rat model of Parkinson's disease. (2000 Jul)
97. Protection and repair of the nigrostriatal dopaminergic system by GDNF in vivo. (1995 Jan 26)
98. Co-grafted embryonic striatum increases the survival of grafted embryonic dopamine neurons. (1998 Oct 5)
99. Transplantation of fetal dopamine neurons in Parkinson's disease: PET [18F]6-L-fluorodopa studies in two patients with putaminal implants. (1992 Feb)
102. Evidence for long-term survival and function of dopaminergic grafts in progressive Parkinson's disease. (1994 Feb)
104. Fatal cyst formation after fetal mesencephalic allograft transplant for Parkinson's disease. (1998 Oct)
105. Optimizing functional imaging protocols for assessing the outcome of fetal cell transplantation in Parkinson's disease. (2011 May 10)
106. Transplantation in Parkinson's disease: PET changes correlate with the amount of grafted tissue. (2003 Aug)
107. Transplantation in the treatment of paralysis agitans (Parkinson's disease). (1992 Oct)
109. Fetal intra-nigral ventral mesencephalon and kidney tissue bridge transplantation restores the nigrostriatal dopamine pathway in hemi-parkinsonian rats. (2001 Jan 19)
110. Subcellular expression and neuroprotective effects of SK channels in human dopaminergic neurons. (2014 Jan 16)
111. Behavioural effects of human fetal dopamine neurons grafted in a rat model of Parkinson's disease. (1986)
112. Autologous adrenal medullary, fetal mesencephalic, and fetal adrenal brain transplantation in Parkinson's disease: a long-term postoperative follow-up. (1991)
113. Neural stem cell technology as a novel treatment for Parkinson's disease. (2001)
114. Transplantation of human fetal tissue from spontaneous abortions to a rodent model of Parkinson's disease. (1996 Jan-Feb)
115. Simultaneous intrastriatal and intranigral fetal dopaminergic grafts in patients with Parkinson disease: a pilot study. Report of three cases. (2002 Mar)
116. Psychiatric status after human fetal mesencephalic tissue transplantation in Parkinson's disease. (1995 Oct 15)
117. Intranigral transplantation of fetal substantia nigra allograft in the hemiparkinsonian rhesus monkey. (1999 Jan-Feb)
118. Growth factors improve immediate survival of embryonic dopamine neurons after transplantation into rats. (1998 Mar 9)
119. Glial cell line-derived neurotrophic factor improves survival of ventral mesencephalic grafts to the 6-hydroxydopamine lesioned striatum. (1997 Aug)
120. Long-term proliferation and dopaminergic differentiation of human mesencephalic neural precursor cells. (2001 Aug)
121. Porcine fetal ventral mesencephalic cells are targets for primed xenoreactive human T cells. (2006)
122. Both apoptosis and necrosis occur early after intracerebral grafting of ventral mesencephalic tissue: a role for protease activation. (2003 Sep)
123. Cryopreservation of porcine fetal ventral mesencephalic tissue for intrastriatal transplantation in Parkinson's disease. (2001)
124. Pathologic findings in retinal pigment epithelial cell implantation for Parkinson disease. (2009 Oct 6)
125. Behavioral and subthalamic effects of combining a fetal ventral mesencephalic transplant in striatum with an electrolytic lesion of the entopeduncular nucleus in the rat with a unilateral 6-OHDA lesion of substantia nigra. (2003 May)
126. Intranigral grafts of fetal ventral mesencephalic tissue in adult 6-hydroxydopamine-lesioned rats can induce behavioral recovery. (1997 May-Jun)
127. Serotonin neuron transplants exacerbate L-DOPA-induced dyskinesias in a rat model of Parkinson's disease. (2007 Jul 25)
128. Eighteen-month course of two patients with grafts of fetal dopamine neurons for severe Parkinson's disease. (1992 Dec)
129. The effects of storage conditions and trophic supplementation on the survival of fetal mesencephalic cells. (1997 May-Jun)
130. Parkin gene inactivation alters behaviour and dopamine neurotransmission in the mouse. (2003 Sep 15)
131. Improved graft survival and striatal reinnervation by microtransplantation of fetal nigral cell suspensions in the rat Parkinson model. (1994 Jan 7)
132. How useful are stem cells in PD therapy? (2009 Dec)
133. Microcarrier enhanced survival of human and rat fetal ventral mesencephalon cells implanted in the rat striatum. (1997 Nov-Dec)
134. Neuroprotection of grafted neurons with a GDNF/caspase inhibitor cocktail. (2001 Aug)
135. PET imaging of serotonin transporters with 4-[18F]-ADAM in a Parkinsonian rat model. (2013)
137. Comparison of fetal mesencephalic grafts, AAV-delivered GDNF, and both combined in an MPTP-induced nonhuman primate Parkinson's model. (2013 Dec)
138. Lazaroids improve the survival of grafted rat embryonic dopamine neurons. (1994 Dec 20)
139. Clinical pattern and risk factors for dyskinesias following fetal nigral transplantation in Parkinson's disease: a double blind video-based analysis. (2009 Feb 15)
140. Additive effects of caspase inhibitor and lazaroid on the survival of transplanted rat and human embryonic dopamine neurons. (2000 Jul)
141. Cryopreservation, survival and function of intrastriatal fetal mesencephalic grafts in a rat model of Parkinson's disease. (1992)
142. Signs of degeneration in 12-22-year old grafts of mesencephalic dopamine neurons in patients with Parkinson's disease. (2011)
143. Adenovirus-mediated over-expression of TGFbeta1 in the striatum decreases dopaminergic cell survival in embryonic nigral grafts. (1999 Jul 13)
144. Efficient early and sustained transduction of human fetal mesencephalon using adeno-associated virus type 2 vectors. (2004)
145. Comparison of embryonic stem cell-derived dopamine neuron grafts and fetal ventral mesencephalic tissue grafts: morphology and function. (2004)
146. Generation of dopaminergic neurons from human fetal mesencephalic progenitors after co-culture with striatal-conditioned media and exposure to lowered oxygen. (2009 Aug 28)
147. Improvements in MPTP-induced object retrieval deficits and behavioral deficits after fetal nigral grafting in monkeys. (1990)
148. GDNF triggers fiber outgrowth of fetal ventral mesencephalic grafts from nigra to striatum in 6-OHDA-lesioned rats. (1996 Nov)
149. Outcome following intrastriatal fetal mesencephalic grafts for Parkinson's patients is directly related to the volume of grafted tissue. (1997 Aug)
150. Forelimb akinesia in the rat Parkinson model: differential effects of dopamine agonists and nigral transplants as assessed by a new stepping test. (1995 May)
151. Embryonic stem cell-derived Pitx3-enhanced green fluorescent protein midbrain dopamine neurons survive enrichment by fluorescence-activated cell sorting and function in an animal model of Parkinson's disease. (2008 Jun)
152. Human fetal dopamine neurons grafted into the striatum in two patients with severe Parkinson's disease. A detailed account of methodology and a 6-month follow-up. (1989 Jun)
153. Unilateral fetal mesencephalic grafting in two patients with Parkinson's disease: short-term result after transplantation. (1996 Nov)
154. Glial cell line-derived neurotrophic factor increases survival, growth and function of intrastriatal fetal nigral dopaminergic grafts. (1996 Dec)
155. Fetal ventral mesencephalic grafts functionally reduce the dopamine D2 receptor supersensitivity in partially dopamine reinnervated host striatum. (2000 Jul)
156. Nerve growth factor increases survival of dopaminergic graft, rescue nigral dopaminergic neurons and restores functional deficits in rat model of Parkinson's disease. (2006 May 1)
157. Olfactory ensheathing cell transplantation restores functional deficits in rat model of Parkinson's disease: a cotransplantation approach with fetal ventral mesencephalic cells. (2004 Aug)
158. Fetal grafting for Parkinson's disease: expression of immune markers in two patients with functional fetal nigral implants. (1997 May-Jun)
160. Influence of cell preparation and target location on the behavioral recovery after striatal transplantation of fetal dopaminergic neurons in a primate model of Parkinson's disease. (2008 Jan)
161. Erythropoietin and GDNF enhance ventral mesencephalic fiber outgrowth and capillary proliferation following neural transplantation in a rodent model of Parkinson's disease. (2006 Jul)
162. Tyrosine hydroxylase immunoreactivity and monoamine and metabolite levels in cryopreserved human fetal ventral mesencephalon. (1993 Jun)
163. Identification of dopaminergic neurons of nigral and ventral tegmental area subtypes in grafts of fetal ventral mesencephalon based on cell morphology, protein expression, and efferent projections. (2005 Jul 6)
164. Cognition following bilateral implants of embryonic dopamine neurons in PD: a double blind study. (2003 Jun 24)
165. Bone marrow-derived mesenchymal stem cell therapy as a candidate disease-modifying strategy in Parkinson's disease and multiple system atrophy. (2009 Mar)
166. Wnt5a-treated midbrain neural stem cells improve dopamine cell replacement therapy in parkinsonian mice. (2008 Jan)
167. Effect of glial cell line-derived neurotrophic factor (GDNF) co-transplantation with fetal ventral mesencephalic cells (VMC) on functional restoration in 6-hydroxydopamine (6-OHDA) lesioned rat model of Parkinson's disease: neurobehavioral, neurochemical and immunohistochemical studies. (2003 Nov)
168. Effects of GDNF pretreatment on function and survival of transplanted fetal ventral mesencephalic cells in the 6-OHDA rat model of Parkinson's disease. (2009 Jun 18)
169. Long-term survival of grafted cells, dopamine synthesis/release, synaptic connections, and functional recovery after transplantation of fetal nigral cells in rats with unilateral 6-OHDA lesions in the nigrostriatal dopamine pathway. (1990 Nov 26)
170. Influence of BDNF on the expression of the dopaminergic phenotype of tissue used for brain transplants. (1997 May 20)
171. Unilateral transplantation of human fetal mesencephalic tissue into the caudate nucleus of patients with Parkinson's disease. (1992 Nov 26)
172. Intracerebral transplantation of fetal ventral mesencephalon for patients with advanced Parkinson's disease. Methodology and 6-month to 1-year follow-up in 3 patients. (1997)
173. Characterization of Lewy body pathology in 12- and 16-year-old intrastriatal mesencephalic grafts surviving in a patient with Parkinson's disease. (2010 Jun 15)
174. Reformation of the nigrostriatal pathway by fetal dopaminergic micrografts into the substantia nigra is critically dependent on the age of the host. (1999 Sep)
175. Additive effect of glial cell line-derived neurotrophic factor and neurotrophin-4/5 on rat fetal nigral explant cultures. (2001)
176. Expression of tyrosine hydroxylase in an immortalized human fetal astrocyte cell line; in vitro characterization and engraftment into the rodent striatum. (1996 Mar-Apr)
177. Individual human serum differs in the amount of antibodies with affinity for pig fetal ventral mesencephalic cells and the ability to lyse these cells by complement activation. (2004)
178. Dopamine-rich grafts alleviate deficits in contralateral response space induced by extensive dopamine depletion in rats. (2013 Sep)
179. General cognitive ability following unilateral and bilateral fetal ventral mesencephalic tissue transplantation for treatment of Parkinson's disease. (1995 Jul)
180. Neuropathological evidence of graft survival and striatal reinnervation after the transplantation of fetal mesencephalic tissue in a patient with Parkinson's disease. (1995 Apr 27)
182. The release of excitatory amino acids, dopamine, and potassium following transplantation of embryonic mesencephalic dopaminergic grafts to the rat striatum, and their effects on dopaminergic neuronal survival in vitro. (2002)
183. Functional improvement with low-dose dopaminergic grafts in hemiparkinsonian rats. (2004 Aug)
184. Effect of GDNF-releasing biodegradable microspheres on the function and the survival of intrastriatal fetal ventral mesencephalic cell grafts. (2006 Jun)
185. Implantation of fetal tissue for the management of Parkinson's disease: a technical note. (1995 May)
187. Salsolinol, a dopamine-derived tetrahydroisoquinoline, induces cell death by causing oxidative stress in dopaminergic SH-SY5Y cells, and the said effect is attenuated by metallothionein. (2004 Apr 16)
188. Behavioral changes in unilaterally 6-hydroxy-dopamine lesioned rats after transplantation of differentiated mouse embryonic stem cells without morphological integration. (2004)
189. Neurotransplantation in Parkinson's disease: from open microsurgery to bilateral stereotactic approach: first clinical trial using microelectrode recording technique. (1994)
190. Liposome-mediated gene transfer to fetal human ventral mesencephalic explant cultures. (2001 Aug 10)
191. GDNF increases the density of cells containing calbindin but not of cells containing calretinin in cultured rat and human fetal nigral tissue. (1999 Jan-Feb)
192. Innovative treatment or ethical headache? Fetal transplantation in Parkinson's disease. (1992 Jun)
193. Differential dissection of the rat E16 ventral mesencephalon and survival and reinnervation of the 6-OHDA-lesioned striatum by a subset of aldehyde dehydrogenase-positive TH neurons. (1997 May-Jun)
194. Functional properties and synaptic integration of genetically labelled dopaminergic neurons in intrastriatal grafts. (2005 May)
195. Deep brain stimulation in Parkinson's disease following fetal nigral transplantation. (2008 Jul 15)
196. Apoptosis in primary cultures of E14 rat ventral mesencephala: time course of dopaminergic cell death and implications for neural transplantation. (1999 Nov)
197. Sham surgery does not ameliorate MPTP-induced behavioral deficits in monkeys. (1995 Jan-Feb)
198. Bilateral fetal mesencephalic grafting in two patients with parkinsonism induced by 1-methyl-4-phenyl-1,2,3,6-tetrahydropyridine (MPTP). (1992 Nov 26)
199. Effects of creatine treatment on the survival of dopaminergic neurons in cultured fetal ventral mesencephalic tissue. (2005)
200. Glial cell line-derived neurotrophic factor-supplemented hibernation of fetal ventral mesencephalic neurons for transplantation in Parkinson disease: long-term storage. (2002 Nov 15)
201. Lewy bodies in grafted neurons in subjects with Parkinson's disease suggest host-to-graft disease propagation. (2008 May)
202. Topology of intrastriatal dopaminergic grafts determines functional and emotional outcome in neurotoxin-lesioned rats. (2011 Jan 1)
203. Effects of cool storage on survival and function of intrastriatal ventral mesencephalic grafts. (1991 Jan 1)
204. The effect of nigral implantation on sensitization to dopamine agonists in 6-hydroxydopamine-lesioned rats. (1997 Aug)
205. Effects of intranigral vs intrastriatal fetal mesencephalic neural grafts on motor behavior disorders in a rat Parkinson model. (2005)
206. Nonviral glial cell-derived neurotrophic factor gene transfer enhances survival of cultured dopaminergic neurons and improves their function after transplantation in a rat model of Parkinson's disease. (2000 Jul 20)
207. Increased survival of dopaminergic neurons in striatal grafts of fetal ventral mesencephalic cells exposed to neurotrophin-3 or glial cell line-derived neurotrophic factor. (2000 Jan-Feb)
208. Expression of dopamine transporter mRNA and its binding site in fetal nigral cells transplanted into the striatum of 6-OHDA lesioned rat. (1996 Jul)
209. Developing stem cell therapies for Parkinson's disease: waiting until the time is right. (2014 Nov 6)
210. Dopaminergic differentiation of neural progenitors derived from placental mesenchymal stem cells in the brains of Parkinson's disease model rats and alleviation of asymmetric rotational behavior. (2012 Jul 23)
211. Restoration of complex sensorimotor behavior and skilled forelimb use by a modified nigral cell suspension transplantation approach in the rat Parkinson model. (1993 Sep)
212. Implantation of c-mycER TAM immortalized human mesencephalic-derived clonal cell lines ameliorates behavior dysfunction in a rat model of Parkinson's disease. (2009 Mar)
213. Glial cell line-derived neurotrophic factor-supplemented hibernation of fetal ventral mesencephalic neurons for transplantation in Parkinson disease: long-term storage. (2003 May)
214. Neural transplantation (auto-adrenal, fetal nigral and fetal adrenal) in Parkinson's disease: the Mexican experience. (1990)
215. Long-term effects of human-to-rat mesencephalic xenografts on rotational behavior, striatal dopamine receptor binding, and mRNA levels. (1995)
216. Cystatin C prevents degeneration of rat nigral dopaminergic neurons: in vitro and in vivo studies. (2005 Feb)
217. CGP 3466 increases survival of cultured fetal dopaminergic neurons. (2003)
218. Long-term improvement in patients with severe Parkinson's disease after implantation of fetal ventral mesencephalic tissue in a cavity of the caudate nucleus: 5-year follow up in 10 patients. Clinica Puerta de Hierro Neural Transplantation Group. (1997 Jun)
219. Growth and functional efficacy of intrastriatal nigral transplants depend on the extent of nigrostriatal degeneration. (2001 Apr 15)
220. Optimal effectiveness of BDNF for fetal nigral transplants coincides with the ontogenic appearance of BDNF in the striatum. (1998 Aug 1)
221. Human embryonic dopamine neurons xenografted to the rat: effects of cryopreservation and varying regional source of donor cells on transplant survival, morphology and function. (1994 Jun 6)
222. Human fetal dopamine neurons grafted in a rat model of Parkinson's disease: ultrastructural evidence for synapse formation using tyrosine hydroxylase immunocytochemistry. (1988)

#### Checking for PMC full-text availability

In [58]:
pmcids_2 = []
for pmid in df2["pmid"]:
    try:
        pmcids_2.append(check_pmc_fulltext(pmid))
    except Exception as e:
        print(f"Error checking PMID {pmid}: {e}")
        pmcids_2.append(None)
    time.sleep(0.4 if not NCBI_API_KEY else 0.15)

df2["pmcid"] = pmcids_2
df2["has_pmc_fulltext"] = df2["pmcid"].notna()
print(f"{df2['has_pmc_fulltext'].sum()} of {len(df2)} papers have PMC full text")

40 of 288 papers have PMC full text

#### Fetching DOIs

In [59]:
doi_map_2 = fetch_dois(df2["pmid"].tolist())
df2["doi"] = df2["pmid"].map(doi_map_2)
print(f"{df2['doi'].notna().sum()} of {len(df2)} papers have a DOI on record")

253 of 288 papers have a DOI on record

#### Checking open acesss availability

In [60]:
oa_results_2 = []
for doi in df2["doi"]:
    try:
        oa_results_2.append(check_unpaywall(doi))
    except Exception as e:
        print(f"Error checking DOI {doi}: {e}")
        oa_results_2.append({"is_oa": False, "oa_url": None})
    time.sleep(0.2)

oa_df_2 = pd.DataFrame(oa_results_2)
df2["unpaywall_is_oa"] = oa_df_2["is_oa"]
df2["unpaywall_url"] = oa_df_2["oa_url"]

df2["has_any_legitimate_access"] = df2["has_pmc_fulltext"] | df2["unpaywall_is_oa"]
print(f"{df2['has_any_legitimate_access'].sum()} of {len(df2)} accessible via PMC or Unpaywall combined")

still_inaccessible_2 = df2[~df2["has_any_legitimate_access"]]
print(f"\n{len(still_inaccessible_2)} still with no automated open route:")
for _, row in still_inaccessible_2.iterrows():
    print(f"- {row['title']} ({row['pubdate']})")

90 of 288 accessible via PMC or Unpaywall combined

198 still with no automated open route:
- Are synucleinopathies prion-like disorders? (2010 Nov)
- Cell transplantation for Parkinson's disease. (2004 Jun)
- Brain imaging after neural transplantation. (2010)
- Parkinson's disease: past, present, and future. (1993 Aug)
- Fetal nigral transplantation as a therapy for Parkinson's disease. (1996 Mar)
- Cell therapy and transplantation in Parkinson's disease. (2001 Apr)
- Neurosurgery for Parkinson's disease. (2001)
- Transplants in Parkinson's disease. (1991)
- Surgical treatment of Parkinson's disease. (1997 Apr)
- PET and SPECT studies in Parkinson's disease. (1997 Apr)
- Neural transplantation in Parkinson's disease. (2000)
- Parkinson's disease and alpha synuclein: is Parkinson's disease a prion-like disorder? (2013 Jan)
- Cell transplantation for the treatment of Parkinson's disease. (2001)
- The future of cell therapies in the treatment of Parkinson's disease. (2007 Oct)
- Motor disturbance and brain functional imaging in Parkinson's disease. (1997)
- Neural transplantation in Parkinson's disease. (2001)
- Neurosurgical horizons in Parkinson's disease. (1993 Jan)
- Transplantation strategies in the treatment of Parkinson's disease: experimental basis and clinical trials. (1989)
- Cell-based therapies in Parkinson's disease. (2009 Jul)
- Stem cell treatment for Parkinson's disease: an update for 2005. (2005 Aug)
- Apoptosis in neuronal development and transplantation: role of caspases and trophic factors. (1999 Mar)
- Fetal dopaminergic transplantation trials and the future of neural grafting in Parkinson's disease. (2013 Jan)
- Intracerebral transplantation of genetically engineered cells for Parkinson's disease: toward clinical application. (2007)
- [ES cell therapy for Parkinson's disease]. (2004 Sep)
- Neural transplantation, trophic factors and Parkinson's disease. (1994)
- [Cell therapy and other neuroregenerative strategies in Parkinson's disease (I)]. (2005 Nov 16-30)
- Evidence-based medical review update: pharmacological and surgical treatments of Parkinson's disease: 2001 to 2004. (2005 May)
- Midbrain-derived neural stem cells: from basic science to therapeutic approaches. (2004 Oct)
- Growth factors in Parkinson's disease. (1994)
- Frontiers in the surgical treatment of Parkinson's disease. (2008 Jun)
- Surgical treatment of Parkinson's disease. (1996 Oct)
- Transplantation of fetal mesencephalic tissue in Parkinson's patients. (1994)
- Medical and surgical treatment of Parkinson's disease. Strategies to slow symptom progression and improve quality of life. (1999 Aug)
- Neurosurgical interventions in the treatment of idiopathic Parkinson disease: neurostimulation and neural implantation. (1999 Jan)
- [Cell therapy and other neuroregenerative strategies in Parkinson's disease (II)]. (2005 Dec 1-15)
- Levodopa neurotoxicity: experimental studies versus clinical relevance. (1998 Jun)
- Neural transplantation in Parkinson's disease and its effects on rest tremor: a review of the literature. (1998)
- The future of cell-based transplantation therapies for neurodegenerative disorders. (2003 Dec)
- Positive potential of fetal nigral implants for Parkinson disease. (2004 Jun)
- Ethical aspects of neural tissue transplantation. (1999 Sep)
- Functional imaging of Parkinson's disease: is it possible to detect brain areas for specific symptoms? (1999)
- [Neural transplantation for the treatment of Parkinson's disease. Update and future]. (2004 Dec)
- Monitoring neuroprotection and restorative therapies in Parkinson's disease with PET. (2000)
- Bilateral fetal nigral transplantation into the postcommissural putamen in Parkinson's disease. (1995 Sep)
- Grafts in the treatment of Parkinson's disease: animal models. (1993 Jan-Mar)
- In vivo imaging of the integration and function of nigral grafts in clinical trials. (2012)
- The therapeutic potential of neurotrophic factors in the treatment of Parkinson's disease. (1993 Nov)
- Derivation of functional dopamine neurons from embryonic stem cells. (2007)
- Growth factors rescue embryonic dopamine neurons from programmed cell death. (1996 Jul)
- Dopaminergic transplants in patients with Parkinson's disease: neuroanatomical correlates of clinical recovery. (1997 Mar)
- Long-term evaluation of bilateral fetal nigral transplantation in Parkinson disease. (1999 Feb)
- Dyskinesia after fetal cell transplantation for parkinsonism: a PET study. (2002 Nov)
- [Surgical treatment of Parkinson's disease]. (1993 Nov)
- [Cellular transplants for Parkinson's disease]. (1991 May)
- Functional fetal nigral grafts in a patient with Parkinson's disease: chemoanatomic, ultrastructural, and metabolic studies. (1996 Jun 24)
- Efficacy of grafted immortalized dopamine neurons in an animal model of parkinsonism: a review. (1998 Sep)
- Pallidal neuronal discharge in Parkinson's disease following intraputamenal fetal mesencephalic allograft. (2011 Mar)
- [Surgical treatment of Parkinson's disease]. (2004)
- Brain grafting may reverse loss of responsiveness to levodopa therapy in Parkinson's disease. (1988 Feb)
- Cryopreservation, culture, and transplantation of human fetal mesencephalic tissue into monkeys. (1988 Nov 4)
- Neural transplantation cannula and microinjector system: experimental and clinical experience. Technical note. (2000 Mar)
- Serotonin neuron loss and nonmotor symptoms continue in Parkinson's patients treated with dopamine grafts. (2012 Apr 4)
- Transplantation of fetal mesencephalic tissue in Parkinson's disease. (1995 Sep 14)
- Homogenous fetal dopaminergic cell transplantation in rat striatum by cell suspension methods. (1993 Jun)
- Fetal nigral grafts survive and mediate clinical benefit in a patient with Parkinson's disease. (1998 May)
- Improving the survival of grafted embryonic dopamine neurons in rodent models of Parkinson's disease. (2000)
- Protection and repair of the nigrostriatal dopaminergic system by GDNF in vivo. (1995 Jan 26)
- Co-grafted embryonic striatum increases the survival of grafted embryonic dopamine neurons. (1998 Oct 5)
- Transplantation of fetal dopamine neurons in Parkinson's disease: PET [18F]6-L-fluorodopa studies in two patients with putaminal implants. (1992 Feb)
- Evidence for long-term survival and function of dopaminergic grafts in progressive Parkinson's disease. (1994 Feb)
- [Restoration of brain function by cell transplantation]. (2003 Mar)
- Fatal cyst formation after fetal mesencephalic allograft transplant for Parkinson's disease. (1998 Oct)
- Transplantation in Parkinson's disease: PET changes correlate with the amount of grafted tissue. (2003 Aug)
- Transplantation in the treatment of paralysis agitans (Parkinson's disease). (1992 Oct)
- Age-related decline in the dopaminergic nigrostriatal system: the oxidative hypothesis and protective strategies. (1992)
- Fetal intra-nigral ventral mesencephalon and kidney tissue bridge transplantation restores the nigrostriatal dopamine pathway in hemi-parkinsonian rats. (2001 Jan 19)
- Behavioural effects of human fetal dopamine neurons grafted in a rat model of Parkinson's disease. (1986)
- Neural stem cell technology as a novel treatment for Parkinson's disease. (2001)
- Transplantation of human fetal tissue from spontaneous abortions to a rodent model of Parkinson's disease. (1996 Jan-Feb)
- Simultaneous intrastriatal and intranigral fetal dopaminergic grafts in patients with Parkinson disease: a pilot study. Report of three cases. (2002 Mar)
- Psychiatric status after human fetal mesencephalic tissue transplantation in Parkinson's disease. (1995 Oct 15)
- Growth factors improve immediate survival of embryonic dopamine neurons after transplantation into rats. (1998 Mar 9)
- Glial cell line-derived neurotrophic factor improves survival of ventral mesencephalic grafts to the 6-hydroxydopamine lesioned striatum. (1997 Aug)
- Long-term proliferation and dopaminergic differentiation of human mesencephalic neural precursor cells. (2001 Aug)
- Cryopreservation of porcine fetal ventral mesencephalic tissue for intrastriatal transplantation in Parkinson's disease. (2001)
- Eighteen-month course of two patients with grafts of fetal dopamine neurons for severe Parkinson's disease. (1992 Dec)
- Parkin gene inactivation alters behaviour and dopamine neurotransmission in the mouse. (2003 Sep 15)
- Improved graft survival and striatal reinnervation by microtransplantation of fetal nigral cell suspensions in the rat Parkinson model. (1994 Jan 7)
- How useful are stem cells in PD therapy? (2009 Dec)
- Neuroprotection of grafted neurons with a GDNF/caspase inhibitor cocktail. (2001 Aug)
- Neuropathology of fetal nigral grafts in patients with Parkinson's disease. (1998)
- Clinical pattern and risk factors for dyskinesias following fetal nigral transplantation in Parkinson's disease: a double blind video-based analysis. (2009 Feb 15)
- Additive effects of caspase inhibitor and lazaroid on the survival of transplanted rat and human embryonic dopamine neurons. (2000 Jul)
- Cryopreservation, survival and function of intrastriatal fetal mesencephalic grafts in a rat model of Parkinson's disease. (1992)
- Adenovirus-mediated over-expression of TGFbeta1 in the striatum decreases dopaminergic cell survival in embryonic nigral grafts. (1999 Jul 13)
- Generation of dopaminergic neurons from human fetal mesencephalic progenitors after co-culture with striatal-conditioned media and exposure to lowered oxygen. (2009 Aug 28)
- Improvements in MPTP-induced object retrieval deficits and behavioral deficits after fetal nigral grafting in monkeys. (1990)
- GDNF triggers fiber outgrowth of fetal ventral mesencephalic grafts from nigra to striatum in 6-OHDA-lesioned rats. (1996 Nov)
- Outcome following intrastriatal fetal mesencephalic grafts for Parkinson's patients is directly related to the volume of grafted tissue. (1997 Aug)
- Human fetal dopamine neurons grafted into the striatum in two patients with severe Parkinson's disease. A detailed account of methodology and a 6-month follow-up. (1989 Jun)
- Unilateral fetal mesencephalic grafting in two patients with Parkinson's disease: short-term result after transplantation. (1996 Nov)
- Glial cell line-derived neurotrophic factor increases survival, growth and function of intrastriatal fetal nigral dopaminergic grafts. (1996 Dec)
- Fetal ventral mesencephalic grafts functionally reduce the dopamine D2 receptor supersensitivity in partially dopamine reinnervated host striatum. (2000 Jul)
- Nerve growth factor increases survival of dopaminergic graft, rescue nigral dopaminergic neurons and restores functional deficits in rat model of Parkinson's disease. (2006 May 1)
- Fetal grafting for Parkinson's disease: expression of immune markers in two patients with functional fetal nigral implants. (1997 May-Jun)
- Transplantation of embryonic dopamine neurons for severe Parkinson's disease. (2001 Jul 12)
- Erythropoietin and GDNF enhance ventral mesencephalic fiber outgrowth and capillary proliferation following neural transplantation in a rodent model of Parkinson's disease. (2006 Jul)
- Tyrosine hydroxylase immunoreactivity and monoamine and metabolite levels in cryopreserved human fetal ventral mesencephalon. (1993 Jun)
- Effect of glial cell line-derived neurotrophic factor (GDNF) co-transplantation with fetal ventral mesencephalic cells (VMC) on functional restoration in 6-hydroxydopamine (6-OHDA) lesioned rat model of Parkinson's disease: neurobehavioral, neurochemical and immunohistochemical studies. (2003 Nov)
- Effects of GDNF pretreatment on function and survival of transplanted fetal ventral mesencephalic cells in the 6-OHDA rat model of Parkinson's disease. (2009 Jun 18)
- Long-term survival of grafted cells, dopamine synthesis/release, synaptic connections, and functional recovery after transplantation of fetal nigral cells in rats with unilateral 6-OHDA lesions in the nigrostriatal dopamine pathway. (1990 Nov 26)
- Influence of BDNF on the expression of the dopaminergic phenotype of tissue used for brain transplants. (1997 May 20)
- Intracerebral transplantation of fetal ventral mesencephalon for patients with advanced Parkinson's disease. Methodology and 6-month to 1-year follow-up in 3 patients. (1997)
- Characterization of Lewy body pathology in 12- and 16-year-old intrastriatal mesencephalic grafts surviving in a patient with Parkinson's disease. (2010 Jun 15)
- Reformation of the nigrostriatal pathway by fetal dopaminergic micrografts into the substantia nigra is critically dependent on the age of the host. (1999 Sep)
- Additive effect of glial cell line-derived neurotrophic factor and neurotrophin-4/5 on rat fetal nigral explant cultures. (2001)
- General cognitive ability following unilateral and bilateral fetal ventral mesencephalic tissue transplantation for treatment of Parkinson's disease. (1995 Jul)
- Neuropathological evidence of graft survival and striatal reinnervation after the transplantation of fetal mesencephalic tissue in a patient with Parkinson's disease. (1995 Apr 27)
- Dopaminergic transplants in experimental parkinsonism: cellular mechanisms of graft-induced functional recovery. (1992 Oct)
- Functional improvement with low-dose dopaminergic grafts in hemiparkinsonian rats. (2004 Aug)
- Effect of GDNF-releasing biodegradable microspheres on the function and the survival of intrastriatal fetal ventral mesencephalic cell grafts. (2006 Jun)
- Implantation of fetal tissue for the management of Parkinson's disease: a technical note. (1995 May)
- [Regeneration of the retina using pigment epithelial cell transplantation]. (2002 Dec)
- Salsolinol, a dopamine-derived tetrahydroisoquinoline, induces cell death by causing oxidative stress in dopaminergic SH-SY5Y cells, and the said effect is attenuated by metallothionein. (2004 Apr 16)
- Neurotransplantation in Parkinson's disease: from open microsurgery to bilateral stereotactic approach: first clinical trial using microelectrode recording technique. (1994)
- Liposome-mediated gene transfer to fetal human ventral mesencephalic explant cultures. (2001 Aug 10)
- Innovative treatment or ethical headache? Fetal transplantation in Parkinson's disease. (1992 Jun)
- Functional properties and synaptic integration of genetically labelled dopaminergic neurons in intrastriatal grafts. (2005 May)
- Deep brain stimulation in Parkinson's disease following fetal nigral transplantation. (2008 Jul 15)
- Apoptosis in primary cultures of E14 rat ventral mesencephala: time course of dopaminergic cell death and implications for neural transplantation. (1999 Nov)
- Effects of creatine treatment on the survival of dopaminergic neurons in cultured fetal ventral mesencephalic tissue. (2005)
- Lewy bodies in grafted neurons in subjects with Parkinson's disease suggest host-to-graft disease propagation. (2008 May)
- Topology of intrastriatal dopaminergic grafts determines functional and emotional outcome in neurotoxin-lesioned rats. (2011 Jan 1)
- Effects of cool storage on survival and function of intrastriatal ventral mesencephalic grafts. (1991 Jan 1)
- The effect of nigral implantation on sensitization to dopamine agonists in 6-hydroxydopamine-lesioned rats. (1997 Aug)
- Effects of intranigral vs intrastriatal fetal mesencephalic neural grafts on motor behavior disorders in a rat Parkinson model. (2005)
- Nonviral glial cell-derived neurotrophic factor gene transfer enhances survival of cultured dopaminergic neurons and improves their function after transplantation in a rat model of Parkinson's disease. (2000 Jul 20)
- Dopaminergic differentiation of neural progenitors derived from placental mesenchymal stem cells in the brains of Parkinson's disease model rats and alleviation of asymmetric rotational behavior. (2012 Jul 23)
- Restoration of complex sensorimotor behavior and skilled forelimb use by a modified nigral cell suspension transplantation approach in the rat Parkinson model. (1993 Sep)
- Implantation of c-mycER TAM immortalized human mesencephalic-derived clonal cell lines ameliorates behavior dysfunction in a rat model of Parkinson's disease. (2009 Mar)
- Glial cell line-derived neurotrophic factor-supplemented hibernation of fetal ventral mesencephalic neurons for transplantation in Parkinson disease: long-term storage. (2003 May)
- Neural transplantation (auto-adrenal, fetal nigral and fetal adrenal) in Parkinson's disease: the Mexican experience. (1990)
- Long-term effects of human-to-rat mesencephalic xenografts on rotational behavior, striatal dopamine receptor binding, and mRNA levels. (1995)
- CGP 3466 increases survival of cultured fetal dopaminergic neurons. (2003)
- Long-term improvement in patients with severe Parkinson's disease after implantation of fetal ventral mesencephalic tissue in a cavity of the caudate nucleus: 5-year follow up in 10 patients. Clinica Puerta de Hierro Neural Transplantation Group. (1997 Jun)
- Human embryonic dopamine neurons xenografted to the rat: effects of cryopreservation and varying regional source of donor cells on transplant survival, morphology and function. (1994 Jun 6)
- Human fetal dopamine neurons grafted in a rat model of Parkinson's disease: ultrastructural evidence for synapse formation using tyrosine hydroxylase immunocytochemistry. (1988)
- Glial cell line-derived neurotrophic factor improves intrastriatal graft survival of stored dopaminergic cells. (1998 Mar)
- Inhibitors of p38 MAP kinase increase the survival of transplanted dopamine neurons. (2001 Feb 9)
- Implantation of bioactive growth factor-secreting rods enhances fetal dopaminergic graft survival, outgrowth density, and functional recovery in a rat model of Parkinson's disease. (2000 Jul)
- Time-dependent expression of donor- and host-specific major histocompatibility complex class I and II antigens in allogeneic dopamine-rich macro- and micrografts: comparison of two different grafting protocols. (1998 Jan)
- Distinct efficacy of pre-differentiated versus intact fetal mesencephalon-derived human neural progenitor cells in alleviating rat model of Parkinson's disease. (2004 Jun)
- Noninvasive dopamine determination by reversed phase HPLC in the medium of free-floating roller tube cultures of rat fetal ventral mesencephalon: a tool to assess dopaminergic tissue prior to grafting. (1996)
- Dopaminergic transplants suppress L-DOPA-induced Fos expression in the dopamine-depleted striatum in a rat model of Parkinson's disease. (1996 Jul 15)
- Chronic treatment with levodopa and/or selegiline does not affect behavioral recovery induced by fetal ventral mesencephalic grafts in unilaterally 6-hydroxydopamine-lesioned rats. (1994 Dec)
- Bridging nigrostriatal pathway with fibroblast growth factor-primed peripheral nerves and fetal ventral mesencephalon transplant recuperates from deficits in parkinsonian rats. (2006)
- Non-dopaminergic neurons in ventral mesencephalic transplants make widespread axonal connections in the host brain. (2008 Sep)
- Preliminary report on the use of fetal tissue transplantation to correct MPTP-induced Parkinson-like syndrome in primates. (1985)
- [Simultaneous transplantation of fetal mesencephalic cells to the striatum and globus pallidus of rats with lesions induced by 6-hydroxydopamine]. (1998 Apr)
- Delta opioid peptide augments functional effects and intrastriatal graft survival of rat fetal ventral mesencephalic cells. (2001 Jan-Feb)
- Effects of perceived treatment on quality of life and medical outcomes in a double-blind placebo surgery trial. (2004 Apr)
- Serotonergic neurons mediate dyskinesia side effects in Parkinson's patients with neural transplants. (2010 Jun 30)
- Clinical correlates of [18F]fluorodopa uptake in five grafted parkinsonian patients. (1995 Oct)
- A fetal nigral graft prevents behavioral supersensitivity associated with repeated injections of L-dopa in 6-OHDA rats. Correlation with D1 and D2 receptors. (1993 Sep)

#### Fetching citation counts

In [61]:
citation_counts_2 = []
for doi in df2["doi"]:
    try:
        citation_counts_2.append(fetch_citation_count(doi))
    except Exception as e:
        print(f"Error fetching citation count for {doi}: {e}")
        citation_counts_2.append(None)
    time.sleep(1.0)

df2["citation_count"] = citation_counts_2
print(f"{df2['citation_count'].notna().sum()} of {len(df2)} papers have a citation count")

Error fetching citation count for 10.1111/j.1469-7580.2006.00654.x: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1111/j.1469-7580.2006.00654.x?fields=citationCount
Error fetching citation count for 10.1016/s0006-8993(98)00120-6: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1016/s0006-8993(98)00120-6?fields=citationCount
Error fetching citation count for 10.3171/jns.2000.92.5.0863: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.3171/jns.2000.92.5.0863?fields=citationCount
Error fetching citation count for 10.1111/j.1460-9568.2004.03770.x: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1111/j.1460-9568.2004.03770.x?fields=citationCount
Error fetching citation count for 10.3727/000000007783464975: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.3727/000000007783464975?fields=citationCount
Error fetching citation count for 10.1007/978-3-7091-9160-6_14: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1007/978-3-7091-9160-6_14?fields=citationCount
Error fetching citation count for 10.1002/syn.10208: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1002/syn.10208?fields=citationCount
Error fetching citation count for 10.1016/0361-9230(91)90050-t: 429 Client Error:  for url: https://api.semanticscholar.org/graph/v1/paper/DOI:10.1016/0361-9230(91)90050-t?fields=citationCount
241 of 288 papers have a citation count

### Angle 3: MoA and GID risk

#### Searching papers

In [62]:
search_result = esearch(angle3_query, retmax=50)
pmids = search_result["esearchresult"]["idlist"]
print(f"Total hits: {search_result['esearchresult']['count']}")

df3 = esummary(pmids)
df3["rank"] = range(1, len(df3) + 1)

df3 = enforce_date_cutoff(df3, cutoff_year=2014)

Total hits: 20

#### Pubtype classification

In [63]:
is_review_3 = df3["pubtypes"].apply(lambda types: bool(set(types) & NON_PRIMARY_TYPES))
reviews_df_3  = df3[is_review_3].reset_index(drop=True)
primary_df_3  = df3[~is_review_3].reset_index(drop=True)

print(f"Reviews: {len(reviews_df_3)}")
print(f"Primary literature: {len(primary_df_3)}")

Reviews: 6
Primary literature: 14

In [64]:
print("=== Primary literature ===")
for _, row in primary_df_3.iterrows():
    print(f"{row['rank']}. {row['title']} ({row['pubdate']})")

print("\n=== Reviews ===")
for _, row in reviews_df_3.iterrows():
    print(f"{row['rank']}. {row['title']} ({row['pubdate']})")

=== Primary literature ===
5. Effect of levodopa priming on dopamine neuron transplant efficacy and induction of abnormal involuntary movements in parkinsonian rats. (2009 Jul 1)
7. Amphetamine-induced dyskinesia in the transplanted hemi-Parkinsonian mouse. (2012)
9. Pharmacological modulation of amphetamine-induced dyskinesia in transplanted hemi-parkinsonian rats. (2012 Oct)
10. Understanding and prevention of "therapy-" induced dyskinesias. (2012)
11. Priming for L-DOPA-induced abnormal involuntary movements increases the severity of amphetamine-induced dyskinesia in grafted rats. (2009 Sep)
12. Serotonergic and dopaminergic mechanisms in graft-induced dyskinesia in a rat model of Parkinson's disease. (2012 Sep)
13. Anatomy of Graft-induced Dyskinesias: Circuit Remodeling in the Parkinsonian Striatum. (2012 Mar 1)
14. Graft placement and uneven pattern of reinnervation in the striatum is important for development of graft-induced dyskinesia. (2006 Mar)
15. The anti-dyskinetic effect of dopamine receptor blockade is enhanced in parkinsonian rats following dopamine neuron transplantation. (2014 Feb)
16. Role of Serotonin Neurons in L-DOPA- and Graft-Induced Dyskinesia in a Rat Model of Parkinson's Disease. (2012)
17. Extent of pre-operative L-DOPA-induced dyskinesia predicts the severity of graft-induced dyskinesia after fetal dopamine cell transplantation. (2011 Dec)
18. Impact of dopamine versus serotonin cell transplantation for the development of graft-induced dyskinesia in a rat Parkinson model. (2012 Aug 27)
19. The impact of graft size on the development of dyskinesia following intrastriatal grafting of embryonic dopamine neurons in the rat. (2006 May)
20. The importance of A9 dopaminergic neurons in mediating the functional benefits of fetal ventral mesencephalon transplants and levodopa-induced dyskinesias. (2007 Mar)

=== Reviews ===
1. Understanding graft-induced dyskinesia. (2010 Sep)
2. L-DOPA- and graft-induced dyskinesia following transplantation. (2012)
3. L-DOPA and graft-induced dyskinesia: different treatment, same story? (2013 Jul)
4. Clinical and experimental experiences of graft-induced dyskinesia. (2011)
6. Neural grafting in Parkinson's disease unraveling the mechanisms underlying graft-induced dyskinesia. (2010)
8. The future of cell therapies in the treatment of Parkinson's disease. (2007 Oct)

#### Checking for full PMC availability

In [65]:
pmcids_3 = []
for pmid in df3["pmid"]:
    try:
        pmcids_3.append(check_pmc_fulltext(pmid))
    except Exception as e:
        print(f"Error checking PMID {pmid}: {e}")
        pmcids_3.append(None)
    time.sleep(0.4 if not NCBI_API_KEY else 0.15)

df3["pmcid"] = pmcids_3
df3["has_pmc_fulltext"] = df3["pmcid"].notna()
print(f"{df3['has_pmc_fulltext'].sum()} of {len(df3)} papers have PMC full text")

4 of 20 papers have PMC full text

#### Fetching DOIs

In [66]:
doi_map_3 = fetch_dois(df3["pmid"].tolist())
df3["doi"] = df3["pmid"].map(doi_map_3)
print(f"{df3['doi'].notna().sum()} of {len(df3)} papers have a DOI on record")

20 of 20 papers have a DOI on record

#### Checking open access availability

In [67]:
oa_results_3 = []
for doi in df3["doi"]:
    try:
        oa_results_3.append(check_unpaywall(doi))
    except Exception as e:
        print(f"Error checking DOI {doi}: {e}")
        oa_results_3.append({"is_oa": False, "oa_url": None})
    time.sleep(0.2)

oa_df_3 = pd.DataFrame(oa_results_3)
df3["unpaywall_is_oa"] = oa_df_3["is_oa"]
df3["unpaywall_url"] = oa_df_3["oa_url"]

df3["has_any_legitimate_access"] = df3["has_pmc_fulltext"] | df3["unpaywall_is_oa"]
print(f"{df3['has_any_legitimate_access'].sum()} of {len(df3)} accessible via PMC or Unpaywall combined")

still_inaccessible_3 = df3[~df3["has_any_legitimate_access"]]
print(f"\n{len(still_inaccessible_3)} still with no automated open route:")
for _, row in still_inaccessible_3.iterrows():
    print(f"- {row['title']} ({row['pubdate']})")

11 of 20 accessible via PMC or Unpaywall combined

9 still with no automated open route:
- Understanding graft-induced dyskinesia. (2010 Sep)
- L-DOPA- and graft-induced dyskinesia following transplantation. (2012)
- L-DOPA and graft-induced dyskinesia: different treatment, same story? (2013 Jul)
- Clinical and experimental experiences of graft-induced dyskinesia. (2011)
- Neural grafting in Parkinson's disease unraveling the mechanisms underlying graft-induced dyskinesia. (2010)
- The future of cell therapies in the treatment of Parkinson's disease. (2007 Oct)
- Priming for L-DOPA-induced abnormal involuntary movements increases the severity of amphetamine-induced dyskinesia in grafted rats. (2009 Sep)
- Extent of pre-operative L-DOPA-induced dyskinesia predicts the severity of graft-induced dyskinesia after fetal dopamine cell transplantation. (2011 Dec)
- Impact of dopamine versus serotonin cell transplantation for the development of graft-induced dyskinesia in a rat Parkinson model. (2012 Aug 27)

#### Fetching citation counts

In [68]:
citation_counts_3 = []
for doi in df3["doi"]:
    try:
        citation_counts_3.append(fetch_citation_count(doi))
    except Exception as e:
        print(f"Error fetching citation count for {doi}: {e}")
        citation_counts_3.append(None)
    time.sleep(1.0)

df3["citation_count"] = citation_counts_3
print(f"{df3['citation_count'].notna().sum()} of {len(df3)} papers have a citation count")

20 of 20 papers have a citation count

## Step 3: Building final corpus (with cutoff)

#### Select top_n papers from each query by union of relevance and citations
- A fixed cutoff was chosen for each individual ranking - relevance AND citations. Namely: top_n=10 papers for both angle1 and angle2 searches; and top_n=5 for the narrower angle3.

In [69]:
df_selected = select_by_either_metric(df, top_n=10)  # arbitrary cut-off of 10 papers 
df2_selected = select_by_either_metric(df2, top_n=10) # arbitrary cut-off of 10 papers
df3_selected = select_by_either_metric(df3, top_n=5) # arbitrary cut-off of 5 papers

print(f"Angle1 selected: {len(df_selected)}, Angle2 selected: {len(df2_selected)}, Angle3 selected: {len(df3_selected)}")

Angle1 selected: 16, Angle2 selected: 20, Angle3 selected: 10

In [68]:
df_selected

,pmid,title,journal,pubdate,pubtypes,rank,pub_year,pmcid,has_pmc_fulltext,doi,unpaywall_is_oa,unpaywall_url,has_any_legitimate_access,citation_count
0,21651331,Cell-based therapies for Parkinson's disease.,Expert review of neurotherapeutics,2011 Jun,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",1,2011.0,None,False,10.1586/ern.11.33,False,None,False,54
1,20489615,Cell transplantation in Parkinson's disease: problems and perspectives.,Current opinion in neurology,2010 Aug,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",2,2010.0,None,False,10.1097/WCO.0b013e32833b1f62,True,https://zenodo.org/record/3429361,True,65
2,23298521,Stem cells and the treatment of Parkinson's disease.,Experimental neurology,2014 Oct,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",3,2014.0,None,False,10.1016/j.expneurol.2012.12.017,False,None,False,28
3,19007882,Cell replacement therapy for Parkinson's disease.,Biochimica et biophysica acta,2009 Jul,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",4,2009.0,None,False,10.1016/j.bbadis.2008.10.007,True,https://hal.science/hal-00492064,True,83
4,30890881,Stem cells and regenerative therapies for Parkinson's disease.,Degenerative neurological and neuromuscular disease,2012,"[Journal Article, Review]",5,2012.0,PMC6065567,True,10.2147/DNND.S16087,True,https://www.dovepress.com/getfile.php?fileID=13337,True,4
5,20887880,Neural grafting in Parkinson's disease Problems and possibilities.,Progress in brain research,2010,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",6,2010.0,None,False,10.1016/S0079-6123(10)84014-2,False,None,False,147
6,25372072,Stem cell therapies for Parkinson's disease: are trials just around the corner?,Regenerative medicine,2014,"[Editorial, Research Support, Non-U.S. Gov't]",7,2014.0,None,False,10.2217/rme.14.43,False,None,False,9
7,17916042,The future of cell therapies in the treatment of Parkinson's disease.,Expert opinion on biological therapy,2007 Oct,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",8,2007.0,None,False,10.1517/14712598.7.10.1487,False,None,False,17
8,25170676,Which patients with Parkinson's disease participate in clinical trials? One centre's experiences with a new cell based therapy trial (TRANSEURO).,Journal of Parkinson's disease,2014,"[Journal Article, Multicenter Study, Randomized Controlled Trial, Research Support, Non-U.S. Gov't]",9,2014.0,None,False,10.3233/JPD-140432,True,https://doaj.org/article/efe6ca6432c043b790ad6c10182c2930,True,47
9,24372386,The future of cell therapies and brain repair: Parkinson's disease leads the way.,Neuropathology and applied neurobiology,2014 Feb,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",10,2014.0,None,False,10.1111/nan.12110,True,https://doi.org/10.1111/nan.12110,True,83
10,15717048,Immune problems in central nervous system cell therapy.,NeuroRx : the journal of the American Society for Experimental NeuroTherapeutics,2004 Oct,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",12,2004.0,PMC534953,True,10.1602/neurorx.1.4.472,True,https://link.springer.com/content/pdf/10.1602%2Fneurorx.1.4.472.pdf,True,142
11,23237903,Fetal dopaminergic transplantation trials and the future of neural grafting in Parkinson's disease.,The Lancet. Neurology,2013 Jan,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",18,2013.0,None,False,10.1016/S1474-4422(12)70295-8,False,None,False,353
12,8797670,The time course of loss of dopaminergic neurons and the gliotic reaction surrounding grafts of embryonic mesencephalon to the striatum.,Experimental neurology,1996 Sep,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",25,1996.0,None,False,10.1006/exnr.1996.0141,False,None,False,218
13,24584936,Anti-amyloid compounds inhibit α-synuclein aggregation induced by protein misfolding cyclic amplification (PMCA).,The Journal of biological chemistry,2014 Apr 25,"[Journal Article, Research Support, Non-U.S. Gov't]",28,2014.0,PMC4002097,True,10.1074/jbc.M113.542340,True,http://www.jbc.org/article/S0021925820415078/pdf,True,78
14,17708336,The effect of truncated human alpha-synuclein (1-120) on dopaminergic cells in a transgenic mouse model of Parkinson's disease.,Cell transplantation,2007,"[Journal Article, Research Support, Non-U.S. Gov't]",36,2007.0,None,False,10.3727/000000007783464911,True,https://doaj.org/article/c04560579e20431992c9023b5b46dbe8,True,66
15,8566192,"Dopaminergic neuronal survival and the effects of bFGF in explant, three dimensional and monolayer cultures of embryonic rat ventral mesencephalon.",Experimental brain research,1995,"[Journal Article, Research Support, Non-U.S. Gov't]",39,1995.0,None,False,10.1007/BF00241123,False,None,False,75

In [69]:
df2_selected

,pmid,title,journal,pubdate,pubtypes,rank,pub_year,pmcid,has_pmc_fulltext,doi,unpaywall_is_oa,unpaywall_url,has_any_legitimate_access,citation_count
0,21901584,Cell therapeutics in Parkinson's disease.,Neurotherapeutics : the journal of the American Society for Experimental NeuroTherapeutics,2011 Oct,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",1,2011.0,PMC3250287,True,10.1007/s13311-011-0069-6,True,https://link.springer.com/content/pdf/10.1007/s13311-011-0069-6.pdf,True,91.0
1,15717042,Cell therapy in Parkinson's disease.,NeuroRx : the journal of the American Society for Experimental NeuroTherapeutics,2004 Oct,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",2,2004.0,PMC534947,True,10.1602/neurorx.1.4.382,True,https://link.springer.com/content/pdf/10.1602%2Fneurorx.1.4.382.pdf,True,124.0
2,7975571,Treatment of Parkinson's disease.,The Western journal of medicine,1994 Sep,"[Journal Article, Review]",3,1994.0,PMC1011414,True,None,False,None,True,NaN
3,21626551,"Parkinson's disease, proteins, and prions: milestones.",Movement disorders : official journal of the Movement Disorder Society,2011 May,"[Historical Article, Journal Article, Review]",4,2011.0,None,False,10.1002/mds.23767,True,https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/mds.23767,True,51.0
4,20846907,Are synucleinopathies prion-like disorders?,The Lancet. Neurology,2010 Nov,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",5,2010.0,None,False,10.1016/S1474-4422(10)70213-1,False,None,False,266.0
5,22936307,α-Synuclein and neuronal cell death.,Molecular neurobiology,2013 Apr,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",6,2013.0,PMC3589663,True,10.1007/s12035-012-8327-0,True,https://link.springer.com/content/pdf/10.1007/s12035-012-8327-0.pdf,True,0.0
6,15198860,Cell transplantation for Parkinson's disease.,Neurological research,2004 Jun,"[Journal Article, Review]",7,2004.0,None,False,10.1179/016164104225017604,False,None,False,NaN
7,20887876,Brain imaging after neural transplantation.,Progress in brain research,2010,"[Journal Article, Review]",8,2010.0,None,False,10.1016/S0079-6123(10)84010-5,False,None,False,23.0
8,23401015,Developing dopaminergic cell therapy for Parkinson's disease--give up or move forward?,Movement disorders : official journal of the Movement Disorder Society,2013 Mar,"[Editorial, Review]",9,2013.0,None,False,10.1002/mds.25378,True,https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/mds.25378,True,78.0
9,8397719,"Parkinson's disease: past, present, and future.",Neuropsychopharmacology : official publication of the American College of Neuropsychopharmacology,1993 Aug,"[Historical Article, Journal Article, Review]",10,1993.0,None,False,10.1038/npp.1993.39,False,None,False,44.0
10,11236774,Transplantation of embryonic dopamine neurons for severe Parkinson's disease.,The New England journal of medicine,2001 Mar 8,"[Clinical Trial, Journal Article, Randomized Controlled Trial, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",53,2001.0,None,False,10.1056/NEJM200103083441002,True,https://www.nejm.org/doi/pdf/10.1056/NEJM200103083441002?articleTools=true,True,1204.0
11,12953276,A double-blind controlled trial of bilateral fetal nigral transplantation in Parkinson's disease.,Annals of neurology,2003 Sep,"[Clinical Trial, Journal Article, Randomized Controlled Trial, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",82,2003.0,None,False,10.1002/ana.10720,True,https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/ana.10720,True,1548.0
12,7830766,Protection and repair of the nigrostriatal dopaminergic system by GDNF in vivo.,Nature,1995 Jan 26,"[Journal Article, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",97,1995.0,None,False,10.1038/373335a0,False,None,False,1137.0
13,12915482,Parkin gene inactivation alters behaviour and dopamine neurotransmission in the mouse.,Human molecular genetics,2003 Sep 15,"[Comparative Study, Journal Article, Research Support, Non-U.S. Gov't]",130,2003.0,None,False,10.1093/hmg/ddg239,False,None,False,511.0
14,7751951,Forelimb akinesia in the rat Parkinson model: differential effects of dopamine agonists and nigral transplants as assessed by a new stepping test.,The Journal of neuroscience : the official journal of the Society for Neuroscience,1995 May,"[Comparative Study, Journal Article, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",150,1995.0,PMC6578238,True,10.1523/JNEUROSCI.15-05-03863.1995,True,https://www.jneurosci.org/content/jneuro/15/5/3863.full.pdf,True,630.0
15,2786405,Human fetal dopamine neurons grafted into the striatum in two patients with severe Parkinson's disease. A detailed account of methodology and a 6-month follow-up.,Archives of neurology,1989 Jun,"[Journal Article, Research Support, Non-U.S. Gov't]",152,1989.0,None,False,10.1001/archneur.1989.00520420033021,False,None,False,544.0
16,1435880,Unilateral transplantation of human fetal mesencephalic tissue into the caudate nucleus of patients with Parkinson's disease.,The New England journal of medicine,1992 Nov 26,"[Case Reports, Clinical Trial, Journal Article, Randomized Controlled Trial, Research Support, Non-U.S. Gov't]",171,1992.0,None,False,10.1056/NEJM199211263272201,True,https://www.nejm.org/doi/pdf/10.1056/NEJM199211263272201?articleTools=true,True,521.0
17,7700284,Neuropathological evidence of graft survival and striatal reinnervation after the transplantation of fetal mesencephalic tissue in a patient with Parkinson's disease.,The New England journal of medicine,1995 Apr 27,"[Case Reports, Journal Article, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",180,1995.0,None,False,10.1056/NEJM199504273321702,False,None,False,922.0
18,1435882,"Bilateral fetal mesencephalic grafting in two patients with parkinsonism induced by 1-methyl-4-phenyl-1,2,3,6-tetrahydropyridine (MPTP).",The New England journal of medicine,1992 Nov 26,"[Case Reports, Clinical Trial, Journal Article, Research Support, Non-U.S. Gov't]",198,1992.0,None,False,10.1056/NEJM199211263272203,True,https://www.nejm.org/doi/pdf/10.1056/NEJM199211263272203?articleTools=true,True,509.0
19,18391963,Lewy bodies in grafted neurons in subjects with Parkinson's disease suggest host-to-graft disease propagation.,Nature medicine,2008 May,"[Journal Article, Research Support, Non-U.S. Gov't]",201,2008.0,None,False,10.1038/nm1746,False,None,False,1810.0

In [71]:
df3_selected

,pmid,title,journal,pubdate,pubtypes,rank,pub_year,pmcid,has_pmc_fulltext,doi,unpaywall_is_oa,unpaywall_url,has_any_legitimate_access,citation_count
0,20868333,Understanding graft-induced dyskinesia.,Regenerative medicine,2010 Sep,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",1,2010.0,None,False,10.2217/rme.10.42,False,None,False,16
1,23195418,L-DOPA- and graft-induced dyskinesia following transplantation.,Progress in brain research,2012,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",2,2012.0,None,False,10.1016/B978-0-444-59575-1.00007-7,False,None,False,14
2,23828589,"L-DOPA and graft-induced dyskinesia: different treatment, same story?","Experimental biology and medicine (Maywood, N.J.)",2013 Jul,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",3,2013.0,None,False,10.1177/1535370213488478,False,None,False,5
3,21907087,Clinical and experimental experiences of graft-induced dyskinesia.,International review of neurobiology,2011,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",4,2011.0,None,False,10.1016/B978-0-12-381328-2.00007-9,False,None,False,9
4,19399877,Effect of levodopa priming on dopamine neuron transplant efficacy and induction of abnormal involuntary movements in parkinsonian rats.,The Journal of comparative neurology,2009 Jul 1,"[Journal Article, Research Support, N.I.H., Extramural]",5,2009.0,PMC2886671,True,10.1002/cne.22037,True,https://www.ncbi.nlm.nih.gov/pmc/articles/2886671,True,40
5,20887881,Neural grafting in Parkinson's disease unraveling the mechanisms underlying graft-induced dyskinesia.,Progress in brain research,2010,"[Journal Article, Research Support, Non-U.S. Gov't, Review]",6,2010.0,None,False,10.1016/S0079-6123(10)84015-4,False,None,False,78
6,19393238,Priming for L-DOPA-induced abnormal involuntary movements increases the severity of amphetamine-induced dyskinesia in grafted rats.,Experimental neurology,2009 Sep,"[Journal Article, Research Support, Non-U.S. Gov't]",11,2009.0,None,False,10.1016/j.expneurol.2009.04.010,False,None,False,51
7,22579773,Serotonergic and dopaminergic mechanisms in graft-induced dyskinesia in a rat model of Parkinson's disease.,Neurobiology of disease,2012 Sep,"[Journal Article, Research Support, Non-U.S. Gov't, Video-Audio Media]",12,2012.0,None,False,10.1016/j.nbd.2012.03.038,True,https://doaj.org/article/1e207e4e620e4951aa04424fd03c5cff,True,42
8,16256359,Graft placement and uneven pattern of reinnervation in the striatum is important for development of graft-induced dyskinesia.,Neurobiology of disease,2006 Mar,"[Journal Article, Research Support, Non-U.S. Gov't]",14,2006.0,None,False,10.1016/j.nbd.2005.09.008,True,https://doaj.org/article/d9298519bc2147b29208360ae35020fa,True,121
9,16406222,The impact of graft size on the development of dyskinesia following intrastriatal grafting of embryonic dopamine neurons in the rat.,Neurobiology of disease,2006 May,"[Journal Article, Research Support, Non-U.S. Gov't]",19,2006.0,None,False,10.1016/j.nbd.2005.11.011,True,https://doaj.org/article/5a41a29fec994d34a44f87068c26e1e0,True,92

#### Corpus: combine selected papers from all queries and remove duplicates

In [73]:
combined = pd.concat(
    [df_selected.assign(query_angle="angle1"), df2_selected.assign(query_angle="angle2"), df3_selected.assign(query_angle="angle3")],
    ignore_index=True
)

In [74]:
corpus = (
    combined
    .groupby("pmid", as_index=False)
    .agg({
        "title": "first", "journal": "first", "pubdate": "first",
        "pubtypes": "first", "pmcid": "first", "has_pmc_fulltext": "first",
        "doi": "first", "unpaywall_is_oa": "first", "unpaywall_url": "first",
        "has_any_legitimate_access": "first",
        "query_angle": lambda x: sorted(set(x)),
    })
)

print(f"Combined before dedup: {len(combined)}, after dedup: {len(corpus)}")

Combined before dedup: 46, after dedup: 46

**Confirm trial design paper (Moore, 2014) is included in corpus**

In [75]:
corpus[corpus["pmid"].isin(["25170676"])]

,pmid,title,journal,pubdate,pubtypes,pmcid,has_pmc_fulltext,doi,unpaywall_is_oa,unpaywall_url,has_any_legitimate_access,query_angle
35,25170676,Which patients with Parkinson's disease participate in clinical trials? One centre's experiences with a new cell based therapy trial (TRANSEURO).,Journal of Parkinson's disease,2014,"[Journal Article, Multicenter Study, Randomized Controlled Trial, Research Support, Non-U.S. Gov't]",None,False,10.3233/JPD-140432,True,https://doaj.org/article/efe6ca6432c043b790ad6c10182c2930,True,[angle1]

**Confirm Freed (PMID 11236774) and Olanow (PMID 12953276) is included in corpus**

In [76]:
corpus[corpus["pmid"].isin(["11236774", "12953276"])]

,pmid,title,journal,pubdate,pubtypes,pmcid,has_pmc_fulltext,doi,unpaywall_is_oa,unpaywall_url,has_any_legitimate_access,query_angle
0,11236774,Transplantation of embryonic dopamine neurons for severe Parkinson's disease.,The New England journal of medicine,2001 Mar 8,"[Clinical Trial, Journal Article, Randomized Controlled Trial, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",None,False,10.1056/NEJM200103083441002,True,https://www.nejm.org/doi/pdf/10.1056/NEJM200103083441002?articleTools=true,True,[angle2]
2,12953276,A double-blind controlled trial of bilateral fetal nigral transplantation in Parkinson's disease.,Annals of neurology,2003 Sep,"[Clinical Trial, Journal Article, Randomized Controlled Trial, Research Support, Non-U.S. Gov't, Research Support, U.S. Gov't, P.H.S.]",None,False,10.1002/ana.10720,True,https://onlinelibrary.wiley.com/doi/pdfdirect/10.1002/ana.10720,True,[angle2]

**Check if Politis et al 2010 (PMID 20592420) - serotoninergic neurons as cause of GIDs -  is included in corpus**

In [77]:
corpus[corpus["pmid"].isin(["20592420"])]

Empty DataFrame
Columns: [pmid, title, journal, pubdate, pubtypes, pmcid, has_pmc_fulltext, doi, unpaywall_is_oa, unpaywall_url, has_any_legitimate_access, query_angle]
Index: []

#### Save corpus list as CSV

In [80]:
corpus.to_csv("transeuro_corpus_pre2015.csv", index=False)
print("Saved to transeuro_corpus_pre2015.csv")

Saved to transeuro_corpus_pre2015.csv

#### Fetch abstracts of finalised corpus

In [81]:
final_pmids = corpus["pmid"].tolist()
abstract_map = fetch_abstracts(final_pmids)
corpus["abstract"] = corpus["pmid"].map(abstract_map)
print(f"{corpus['abstract'].str.len().gt(0).sum()} of {len(corpus)} papers have abstract text")

45 of 46 papers have abstract text

## Step 4: Build frozen context

In [40]:
def build_frozen_context(corpus: pd.DataFrame) -> str:
    """Format the final corpus into one frozen text block for Week 1/2 prompts.
    Ordered chronologically (oldest first), a neutral rule not based on
    judged importance. Each entry is tagged by PMID for traceable citation."""
    ordered = corpus.copy()
    ordered["pub_year_sort"] = ordered["pubdate"].str.extract(r"(\d{4})").astype(float)
    ordered = ordered.sort_values("pub_year_sort").reset_index(drop=True)

    entries = []
    for _, row in ordered.iterrows():
        abstract_text = row["abstract"].strip() if isinstance(row["abstract"], str) else ""
        if not abstract_text:
            abstract_text = "[No abstract available through automated retrieval]"
        entries.append(
            f"[PMID: {row['pmid']}]\n"
            f"Title: {row['title']}\n"
            f"Journal: {row['journal']} ({row['pubdate']})\n"
            f"Abstract: {abstract_text}\n"
        )

    header = (
        f"EVIDENCE PACKAGE — {len(ordered)} sources, all published on or before "
        f"2014-12-31. This is the complete evidence base available for this "
        f"assessment. When referencing a specific claim, cite the source's "
        f"PMID.\n\n"
    )
    return header + "\n---\n".join(entries)

In [82]:
frozen_context = build_frozen_context(corpus)
print(f"Frozen context: {len(frozen_context)} characters (~{len(frozen_context) // 4} tokens)")

with open("transeuro_frozen_context.txt", "w", encoding="utf-8") as f:
    f.write(frozen_context)
print("Saved to transeuro_frozen_context.txt")

Frozen context: 74593 characters (~18648 tokens)
Saved to transeuro_frozen_context.txt

## Pre-LLM step: Loading frozen context and declaring Anthropic API

In [9]:
with open("transeuro_frozen_context.txt", "r", encoding="utf-8") as f:
    frozen_context = f.read()

In [12]:
load_dotenv()
client = Anthropic()
MODEL = "claude-sonnet-5"

## Step 5: Provide frozen context to multi-persona LLM

In [87]:
week1_prompt = f"""You are reviewing a therapeutic development decision as of December 31, 2014.

DECISION: TRANSEURO, a European trial redesigning fetal ventral mesencephalic
tissue transplantation for Parkinson's disease, is about to begin grafting
patients. Assess whether this program is well-justified to proceed, given
everything known up to this date, including the graft-induced dyskinesia
problem observed in earlier (1990s-2000s) NIH-funded trials.

You must reason only from the evidence package below. If you find yourself
drawing on knowledge not contained in this package, say so explicitly rather
than presenting it as if it came from the evidence.

Respond as four independent reviewers, each in their own clearly labeled
section. Each should state their top three concerns and their confidence in
each, citing evidence by PMID.

1. BIOLOGY — success criterion: does the mechanistic rationale for this
   redesign adequately address the known cause of graft-induced dyskinesia?
2. CLINICAL — success criterion: is the trial design and patient selection
   adequate given prior trials' safety and efficacy findings?
3. REGULATORY — success criterion: are known risks adequately characterized
   and mitigated for ethical/regulatory approval to proceed?
4. CMC/MANUFACTURING — success criterion: is fetal tissue sourcing and
   preparation feasible at the scale this trial requires?


EVIDENCE PACKAGE:
{frozen_context}
"""

response = client.messages.create(
    model=MODEL,
    max_tokens=16000,
    temperature=1,
    thinking={
        "type": "adaptive",
        "display": "summarized"
    },
    output_config={
        "effort": "high"
    },
    messages=[{"role": "user", "content": week1_prompt}],
)

week1_output = "".join(
    block.text for block in response.content if block.type == "text"
)

print(week1_output)


with open("week1_output_run2_with_angle3.txt", "w", encoding="utf-8") as f:
    f.write(week1_output)

**Note on method:** The following assessments are constructed strictly from the 46 sources supplied. Where a reviewer's reasoning would normally draw on outside knowledge (e.g., specific TRANSEURO protocol details, exact TRANSEURO patient-age cutoffs, GDNF trial outcomes, iPSC clinical timelines), I flag this explicitly as "not established in this package" rather than asserting it.

---

## 1. BIOLOGY REVIEWER

**Top concern 1 — No single confirmed mechanism for graft-induced dyskinesia (GID).**
The package contains at least five competing, only partially overlapping hypotheses for GID: uneven/patchy striatal reinnervation from graft placement (PMID 16256359), graft size (PMID 16406222), serotonergic neuron contamination of the graft (PMID 22579773), pre-graft L-DOPA priming (PMID 19399877, 19393238), and host inflammatory/immune reaction (PMID 15717048). Review papers as late as 2011–2012 state plainly that "questions still remain as to the underlying mechanism" (PMID 21907087) and that lack of a "truly representative animal model has hindered the search for a conclusive basis" (PMID 21907087). A redesign that targets one or two of these factors (e.g., placement, patient selection) may leave others (e.g., serotonergic contamination) unaddressed.
*Confidence: High* — this gap is stated directly and repeatedly across independent reviews in the package.

**Top concern 2 — Serotonergic-contamination hypothesis is mechanistically plausible but not shown to be manufacturing-controlled.**
Rat data show that dopamine grafts (with or without 5-HT neurons) produce amphetamine-induced GID-like AIMs, and that 5-HT1 agonists (buspirone, 8-OH-DPAT) suppress this behavior (PMID 22579773), implicating serotonergic neurons in aberrant dopamine release causing dyskinesia. Nothing in the package demonstrates that the ventral mesencephalic dissection protocol for the redesigned trial reduces 5-HT neuron content in the graft.
*Confidence: Medium* — biologically plausible mechanism, but the package does not show it has been translated into a manufacturing/dissection fix.

**Top concern 3 — Host-to-graft disease propagation threatens long-term mechanistic durability.**
Lewy bodies have been identified in grafted neurons surviving 11–16 years (PMID 18391963), and multiple sources discuss a prion-like, cell-to-cell alpha-synuclein transmission mechanism (PMID 20846907, 21245577, 21626551, 22936307) that could eventually compromise even a technically well-placed, well-composed graft. Even if acute GID mechanisms are addressed, the biological rationale for durable long-term benefit is incomplete.
*Confidence: Medium* — long-term risk, not a block on proceeding with a well-monitored trial, but weakens the case that this redesign "solves" the biology.

---

## 2. CLINICAL REVIEWER

**Top concern 1 — Reversion to open-label design after two double-blind sham-controlled failures.**
TRANSEURO is described as an "open label multi-centre surgical transplant trial" (PMID 25170676). This follows two double-blind, sham-surgery-controlled trials that found no significant effect on primary global/motor endpoints overall (PMID 11236774: mean global rating 0.0 vs −0.4, not clearly superior; PMID 12953276: p=0.244 overall). These trials specifically demonstrated the importance of blinding to separate true graft effects from placebo/surgical expectation effects. An open-label design in the new trial reintroduces exactly the confound that motivated the earlier blinded trials.
*Confidence: High.*

**Top concern 2 — Enrolled patient population may be enriched for GID risk factors.**
The Cambridge TRANSEURO cohort was younger, more educated, and had better baseline motor function than eligible-but-unenrolled patients, but also had **more motor complications** (i.e., pre-existing dyskinesia) (PMID 25170676). Animal data directly link chronic pre-graft L-DOPA exposure/priming and pre-existing L-DOPA-induced dyskinesia to graft-induced dyskinesia risk (PMID 19399877, 19393238). If enrolled patients are systematically more likely to have motor complications, this raises rather than lowers a known GID risk factor, and the selection is non-random.
*Confidence: Medium-high.*

**Top concern 3 — Uncertain match between age/severity-dependent efficacy signals and current eligibility criteria.**
Benefit in the largest double-blind trial was significant only in patients ≤60 years old (PMID 11236774), and stratified analysis in another trial found treatment effect only in milder-disease patients (PMID 12953276, p=0.006 for milder stratum). The evidence package does not specify whether TRANSEURO's eligibility criteria were calibrated against these prior severity/age findings; this is an open question rather than a documented failure.
*Confidence: Medium (uncertainty stems from absence of protocol detail in the package, not a confirmed flaw).*

---

## 3. REGULATORY REVIEWER

**Top concern 1 — High, well-documented incidence of a serious, largely irreversible adverse effect.**
56% of transplanted patients developed off-medication dyskinesia in one controlled trial (PMID 12953276), and 15% had recurrence of dystonia/dyskinesia in another after initial improvement (PMID 11236774). Because the intervention is neurosurgical implantation of living tissue that cannot be retrieved, this adverse effect is potentially permanent. The mitigations proposed for the redesign (placement, patient selection, possibly reduced graft size) are supported only by preclinical rodent data (PMID 16256359, 16406222, 22579773) and correlational human imaging (cited within 22579773), not by prospective clinical validation of the new protocol itself.
*Confidence: High.*

**Top concern 2 — Unresolved long-term host-to-graft disease propagation risk.**
Evidence of Lewy pathology developing within long-surviving grafts (PMID 18391963) and mechanistic support for prion-like alpha-synuclein transfer (PMID 20846907, 21245577) represent a risk of unknown magnitude and timeline that must be disclosed but cannot currently be quantified for consent purposes.
*Confidence: Medium.*

**Top concern 3 — Ethical/logistic complexity of multi-donor-per-patient fetal tissue procurement across a multi-center European trial.**
Prior trials required as many as four fetal donors per side per patient (PMID 12953276) or four embryos bilaterally (PMID 11236774). The package documents general ethical/practical complications of aborted fetal tissue use (PMID 15717042, 15717048) but does not document a harmonized cross-jurisdictional regulatory/ethical framework for procurement at the scale a multi-site trial would require.
*Confidence: Medium (inferred from absence of documentation in the package rather than from a demonstrated failure).*

---

## 4. CMC/MANUFACTURING REVIEWER

**Top concern 1 — Intrinsically poor and variable dopaminergic neuron survival through preparation and grafting.**
Only 3–10% of grafted dopaminergic neurons typically survive transplantation (PMID 8566192). Enzymatic dissociation alone kills ~30% of dopaminergic neurons before implantation, and of the remainder, up to 87% die within 3 days in monolayer conditions; even in better 3D/explant conditions, the graft microenvironment in vivo causes the majority of neuronal loss within the first 7 days post-implantation due to gliosis/toxicity (PMID 8797670, 8566192). This means outcomes are highly sensitive to handling technique, and no standardized, validated manufacturing process is demonstrated in this package.
*Confidence: High.*

**Top concern 2 — Multi-donor-per-patient requirement is a hard scale constraint.**
Historical trials required up to four fetal donors per side per patient (PMID 12953276) or four embryos per patient (PMID 11236774). Sourcing, timing, and processing this many fresh/cryopreserved fetal tissue samples per patient, synchronized with surgical schedules across multiple European sites, is a nontrivial supply-chain problem that the package's historical trials (largely single or few-center, e.g., PMID 1435880, 2786405) do not demonstrate has been solved at multi-site scale.
*Confidence: Medium-high (inferred scale problem; no source in the package directly confirms or refutes multi-site feasibility).*

**Top concern 3 — No demonstrated quality-control assay for graft composition (e.g., serotonergic neuron content).**
Reviews explicitly flag "variability of functional outcome" tied to "dissection and cellular composition of the graft tissue" as an unresolved problem, calling for tissue "standardized and quality controlled" (PMID 15717042). Given the serotonergic-contamination hypothesis for GID (PMID 22579773), the absence of any documented assay to quantify or control 5-HT neuron content in the final graft product is a specific, unaddressed manufacturing/release-testing gap.
*Confidence: Medium.*

#### Record and save thinking process

In [88]:
week1_thinking = "".join(block.thinking for block in response.content if block.type == "thinking")
print(week1_thinking)

with open("week1_thinking_run2_with_angle3.txt", "w", encoding="utf-8") as f:
    f.write(week1_thinking)

Looking at the clinical evidence systematically, the early open-label trials from the late 1980s and early 1990s showed modest benefits with demonstrated graft survival, but the pivotal double-blind controlled trials in 2001 and 2003 failed their primary endpoints while uncovering a critical problem—graft-induced dyskinesia emerged as a major adverse effect, with one study showing 15% dyskinesia recurrence and another revealing 56% of patients developed off-medication dyskinesia. Now I'm examining the mechanistic work to understand what's driving these outcomes.

The research points to several mechanisms behind graft-induced dyskinesia: uneven reinnervation patterns, graft size effects, serotonergic contamination from the tissue, and L-DOPA priming effects. Multiple review articles have synthesized these competing hypotheses, and there's concerning evidence that Lewy body pathology can propagate from the host brain into the graft—a long-term disease progression risk that wasn't initially appreciated. The TRANSEURO trial represents the most recent major effort, and the patient selection data reveals something important: the trial enrolled younger, more educated patients with better baseline motor function but paradoxically more motor complications than the general Parkinson's population. On the practical side, the manufacturing challenges are substantial—cell survival during tissue preparation is only 3-10%, requiring multiple embryonic donors per patient, and the grafts trigger gliotic reactions. There are also immune considerations to account for.

Now I'm constructing the reviewer perspectives.

For the biology reviewer, the key question is whether TRANSEURO's specific design choices—caudal putamen placement, reduced graft size, no L-DOPA priming exclusion, single-tissue-type grafts, and immunosuppression—actually target the known mechanisms of graft-induced dyskinesia. The evidence clearly implicates uneven reinnervation, graft size, serotonergic contamination, and L-DOPA priming as culprits, and there are design papers describing TRANSEURO's approach, but the abstracts don't explicitly detail how each mechanism is being addressed—for instance, whether tissue dissection refinements specifically reduce serotonergic neuron contamination.

Looking back at the literature, the fundamental problem is that GID's causal mechanism remains incompletely understood—multiple competing hypotheses exist but no conclusive basis has been established, which makes it harder to know if TRANSEURO's design choices are actually targeting the root causes or just addressing correlates.

The clinical reviewer would likely raise concerns about the open-label design, especially given that two prior double-blind sham-controlled trials failed to meet their primary endpoints. The patient selection criteria show an interesting paradox: enrolled participants tend to be younger, more educated, and cognitively/motorically intact, yet they also have more motor complications—which could mean they're inherently predisposed to developing dyskinesias in the first place.

From a regulatory standpoint, there's the matter of informed consent: one trial showed a 56% rate of graft-induced dyskinesias, yet it's unclear whether this risk is adequately disclosed to patients. The open-label design also removes the blinding control that would help distinguish true treatment effects from placebo response.

Then there's the ethical sourcing issue—historical trials required multiple fetal donors per patient (four per side in some cases), and the tissue itself has poor survival rates ex vivo, with significant cell loss during dissociation.  Quality control is inconsistent across sites due to variability in tissue composition and dissection technique, and the reliance on elective abortion tissue creates logistical and supply constraints that would be especially problematic for a multi-center trial requiring synchronized fresh tissue procurement. I need to organize these concerns by reviewer type with confidence levels and citations.

For the biology reviewer, the root cause of graft-induced dyskinesia remains unclear with multiple competing hypotheses about graft placement, size, serotonergic contamination, L-DOPA priming, and host immune responses — review articles acknowledge this uncertainty persists despite decades of research.

The serotonergic contamination hypothesis has some support from rat pharmacology studies showing that serotonin receptor antagonists suppress dyskinesia, plus correlative human PET imaging data, though I should note I don't have access to the full details of those human studies beyond what's cited in the abstracts.

The critical gap here is that the TRANSEURO protocol's tissue dissection approach isn't explicitly shown to reduce serotonergic neuron content—the paper doesn't describe specific refinements addressing this mechanism, so the biological rationale for reduced dyskinesia risk remains unproven.

There's also the longer-term concern that Lewy body pathology has been documented in grafts surviving 11-16 years, suggesting the underlying Parkinson's disease process itself—possibly involving prion-like alpha-synuclein propagation—may eventually compromise even optimally placed and composed grafts, which raises questions about whether any mechanistic fix targeting acute reinnervation patterns can actually ensure durability.

Now looking at the clinical reviewer's perspective: the trial has reverted to an open-label design after two prior double-blind, sham-surgery-controlled trials demonstrated no significant benefit on primary endpoints and revealed how powerfully placebo and surgery effects can confound outcome assessment. Without that blinding, it'll be difficult to separate genuine graft efficacy from expectation effects—a lesson those earlier trials already taught us.

There's also a patient selection bias issue: the Cambridge cohort enrolled in TRANSEURO was younger, more educated, with higher cognitive scores and better baseline motor function, but notably had more motor complications from levodopa than an eligible-but-unenrolled comparison group. Since L-DOPA-induced dyskinesia has been mechanistically linked to graft-induced dyskinesia risk in animal models, this selection toward patients with more baseline motor complications could actually increase GID risk, and it wasn't randomized.

I'm also considering whether age-dependent efficacy patterns might be playing a role here. and whether patient selection criteria alone can adequately mitigate the 56% rate of off-medication dyskinesia observed in prior transplant studies, or if additional tissue preparation and surgical placement modifications are needed to reduce this serious safety signal for an irreversible procedure.

The evidence supporting these mitigations remains largely preclinical—rodent models show promise but haven't been validated clinically in the redesigned protocol. There's also the unresolved question of whether host-to-graft alpha-synuclein propagation could eventually transmit Parkinson's pathology into the graft tissue itself, which is a long-term risk that's difficult to quantify but should be clearly disclosed to patients. Finally, there are ethical concerns around fetal tissue sourcing and informed consent that need addressing.

The manufacturing side presents its own challenges: only 3-10% of dopaminergic neurons survive the transplantation process, with about 30% lost during enzymatic dissociation alone and most of the remaining cells dying within the first week due to the hostile host environment. This means substantial donor tissue is required per patient, and outcomes are highly variable depending on preparation quality.

Beyond that, the multi-donor requirement (up to 4 fetal donors per side in prior trials) creates a significant supply chain bottleneck—tissue needs fresh acquisition, careful processing within tight timeframes, and coordination across multiple European sites, yet the evidence doesn't demonstrate that this scale of synchronized multi-site sourcing is actually feasible. There's also no standardized quality control or composition testing for the ventral mesencephalon tissue itself, so the variability in outcomes is partly driven by inconsistent dissection and cellular composition of the grafts, which remains unresolved.

Now I'm structuring the final answer as four reviewer sections, each laying out the top three concerns with confidence levels and citations, and I'll include a preamble acknowledging that I'm restricted to what's in the evidence package and flagging where I might go beyond it.

## Step 6 : Provide frozen context to LLM through independent persona calls

In [4]:
PERSONAS = {
    "biology": "does the mechanistic rationale for this redesign adequately address the known cause of graft-induced dyskinesia?",
    "clinical": "is the trial design and patient selection adequate given prior trials' safety and efficacy findings?",
    "regulatory": "are known risks adequately characterized and mitigated for ethical/regulatory approval to proceed?",
    "cmc_manufacturing": "is fetal tissue sourcing and preparation feasible at the scale this trial requires?",
}

In [89]:
week2_outputs = {}

for persona_name, success_criterion in PERSONAS.items():
    persona_prompt = f"""You are reviewing a therapeutic development decision as of December 31, 2014,
from the perspective of a single specialist: {persona_name.upper()}.

DECISION: TRANSEURO, a European trial redesigning fetal ventral mesencephalic
tissue transplantation for Parkinson's disease, is about to begin grafting
patients. Assess whether this program is well-justified to proceed, given
everything known up to this date, including the graft-induced dyskinesia
problem observed in earlier (1990s-2000s) NIH-funded trials.

You must reason only from the evidence package below. If you find yourself
drawing on knowledge not contained in this package, say so explicitly rather
than presenting it as if it came from the evidence.

Your specific success criterion: {success_criterion}

State your top three concerns and your confidence in each, citing evidence by PMID.

EVIDENCE PACKAGE:
{frozen_context}
"""

    response = client.messages.create(
        model=MODEL,
        max_tokens=16000,
        temperature=1,
        thinking={"type": "adaptive", "display": "summarized"},
        output_config={"effort": "high"},
        messages=[{"role": "user", "content": persona_prompt}],
    )

    text = "".join(b.text for b in response.content if b.type == "text")
    thinking = "".join(b.thinking for b in response.content if b.type == "thinking")

    print(f"{persona_name}: stop_reason={response.stop_reason}, "
          f"text={len(text)} chars, thinking={len(thinking)} chars")

    week2_outputs[persona_name] = text

    with open(f"week2_{persona_name}_run2_with_angle3.txt", "w", encoding="utf-8") as f:
        f.write(text)
    with open(f"week2_{persona_name}_run2_with_angle3_thinking.txt", "w", encoding="utf-8") as f:
        f.write(thinking)

    time.sleep(1.0)  # light pacing between calls, not strictly required but polite

biology: stop_reason=end_turn, text=6053 chars, thinking=8340 chars
clinical: stop_reason=end_turn, text=6643 chars, thinking=5025 chars
regulatory: stop_reason=end_turn, text=5872 chars, thinking=4738 chars
cmc_manufacturing: stop_reason=end_turn, text=6414 chars, thinking=4217 chars

## Step 7: Provide frozen context to multi-persona agents with one-call tool

In [14]:
def date_capped_pubmed_search(query_term: str, max_results: int = 5) -> str:
    """Date-capped PubMed search for agent use. The cutoff is fixed and
    cannot be altered by the agent's query. Enforced twice: once in the
    query itself, once by re-checking the actual returned pubdate, since
    the query-time filter alone has previously let post-cutoff results through."""
    CUTOFF_YEAR = 2014
    capped_query = f'({query_term}) AND ("1900/01/01"[pdat] : "{CUTOFF_YEAR}/12/31"[pdat])'

    search_result = esearch(capped_query, retmax=max_results, sort="relevance")
    pmids = search_result["esearchresult"]["idlist"]
    if not pmids:
        return "No results found within the date-capped search."

    df = esummary(pmids)
    df["pub_year"] = df["pubdate"].str.extract(r"(\d{4})").astype(float)
    before = len(df)
    df = df[df["pub_year"] <= CUTOFF_YEAR]
    if before - len(df) > 0:
        print(f"[tool enforcement] dropped {before - len(df)} result(s) failing strict date recheck")

    abstracts = fetch_abstracts(df["pmid"].tolist())
    entries = [
        f"[PMID: {row['pmid']}] {row['title']} ({row['pubdate']})\n"
        f"{abstracts.get(row['pmid'], '[abstract unavailable]')}"
        for _, row in df.iterrows()
    ]
    return "\n\n---\n\n".join(entries) if entries else "No results after date enforcement."


PUBMED_TOOL_SCHEMA = {
    "name": "search_pubmed",
    "description": (
        "Search PubMed for relevant literature. Results are automatically "
        "restricted to sources published on or before 2014-12-31; this "
        "restriction cannot be changed or bypassed."
    ),
    "input_schema": {
        "type": "object",
        "properties": {
            "query_term": {"type": "string", "description": "PubMed search query"},
            "max_results": {"type": "integer", "description": "Number of results (default 5)"},
        },
        "required": ["query_term"],
    },
}

In [38]:
def run_week3_persona(persona_name: str, success_criterion: str):
    prompt = f"""You are reviewing a therapeutic development decision as of December 31, 2014,
from the perspective of a single specialist: {persona_name.upper()}.

DECISION: TRANSEURO, a European trial redesigning fetal ventral mesencephalic
tissue transplantation for Parkinson's disease, is about to begin grafting
patients. Assess whether this program is well-justified to proceed.

Your specific success criterion: {success_criterion}

EVIDENCE PACKAGE:
{frozen_context}

You also have access to a PubMed search tool, restricted to sources published
on or before 2014-12-31, if you judge the evidence package above to be
insufficient for a well-supported assessment on any point. 

State your top three concerns and your confidence in each, citing evidence
by PMID from either source."""

    messages = [{"role": "user", "content": prompt}]

    response = client.messages.create(
        model=MODEL, max_tokens=16000, tools=[PUBMED_TOOL_SCHEMA],
        thinking={"type": "adaptive", "display": "summarized"},
        output_config={"effort": "high"}, messages=messages,
    )

    tool_called = any(b.type == "tool_use" for b in response.content)

    if tool_called:
        messages.append({"role": "assistant", "content": response.content})
        tool_results = [
            {"type": "tool_result", "tool_use_id": b.id,
             "content": date_capped_pubmed_search(**b.input)[:8000]}
            for b in response.content if b.type == "tool_use" and b.name == "search_pubmed"
        ]
        tool_results.append({
            "type": "text",
            "text": ("Note: this was your one available tool call for this assessment. "
                     "No further searches are possible. Based on the evidence above and "
                     "the original evidence package, provide your complete final "
                     "assessment now.")
        })
        messages.append({"role": "user", "content": tool_results})

        # No `tools` param here at all — a second call is structurally impossible
        response = client.messages.create(
            model=MODEL, max_tokens=16000,
            thinking={"type": "adaptive", "display": "summarized"},
            output_config={"effort": "high"}, messages=messages,
        )

    text = "".join(b.text for b in response.content if b.type == "text")
    thinking = "".join(b.thinking for b in response.content if b.type == "thinking")
    
    if len(text) == 0:
        print(f"[DIAGNOSTIC] {persona_name}: empty text, dumping response.content structure")
        print([b.type for b in response.content])
        for b in response.content:
            if b.type == "thinking":
                print(f"  thinking (first 300 chars): {b.thinking[:300]}")
            elif b.type == "tool_use":
                print(f"  tool_use: {b.input}")
        with open(f"week3_{persona_name}_DEBUG_raw_response.txt", "w", encoding="utf-8") as f:
            f.write(str(response.content))

    return text, thinking, response.stop_reason, tool_called

In [37]:
def run_week3_persona_with_retry(persona_name: str, success_criterion: str, max_attempts: int = 3):
    for attempt in range(1, max_attempts + 1):
        text, thinking, stop_reason, tool_called = run_week3_persona(persona_name, success_criterion)
        if len(text) > 0:
            return text, thinking, stop_reason, tool_called
        print(f"{persona_name}: empty text on attempt {attempt}, retrying...")
    print(f"{persona_name}: still empty after {max_attempts} attempts, keeping last result")
    return text, thinking, stop_reason, tool_called

In [44]:
week3_outputs = {}
for persona_name, success_criterion in PERSONAS.items():
    try:
        text, thinking, stop_reason, tool_called = run_week3_persona_with_retry(persona_name, success_criterion)
        print(f"{persona_name}: stop_reason={stop_reason}, tool_called={tool_called}, text={len(text)} chars")
        week3_outputs[persona_name] = text
        with open(f"week3_{persona_name}_run4.txt", "w", encoding="utf-8") as f:
            f.write(text)
        with open(f"week3_{persona_name}_run4_thinking.txt", "w", encoding="utf-8") as f:
            f.write(thinking)
    except Exception as e:
        print(f"{persona_name}: FAILED — {e}")
    time.sleep(1.0)

biology: stop_reason=end_turn, tool_called=True, text=5406 chars
clinical: stop_reason=end_turn, tool_called=True, text=5842 chars
regulatory: stop_reason=end_turn, tool_called=True, text=6544 chars
cmc_manufacturing: stop_reason=end_turn, tool_called=True, text=6198 chars

## Step 8: Provide frozen context to multi-persona agents with multi-call tool

In [40]:
MAX_TOOL_ROUNDS = 10  # a safety valve

def run_week4_persona(persona_name: str, success_criterion: str):
    prompt = f"""You are reviewing a therapeutic development decision as of December 31, 2014,
from the perspective of a single specialist: {persona_name.upper()}.

DECISION: TRANSEURO, a European trial redesigning fetal ventral mesencephalic
tissue transplantation for Parkinson's disease, is about to begin grafting
patients. Assess whether this program is well-justified to proceed.

Your specific success criterion: {success_criterion}

EVIDENCE PACKAGE:
{frozen_context}

You also have access to a PubMed search tool, restricted to sources published
on or before 2014-12-31, if you judge the evidence package above to be
insufficient for a well-supported assessment on any point. 

State your top three concerns and your confidence in each, citing evidence
by PMID from either source."""

    messages = [{"role": "user", "content": prompt}]
    all_tool_calls = []
    all_thinking = []
    rounds = 0

    response = client.messages.create(
        model=MODEL, max_tokens=16000, tools=[PUBMED_TOOL_SCHEMA],
        thinking={"type": "adaptive", "display": "summarized"},
        output_config={"effort": "high"}, messages=messages,
    )
    all_thinking.append("".join(b.thinking for b in response.content if b.type == "thinking"))

    while response.stop_reason == "tool_use" and rounds < MAX_TOOL_ROUNDS:
        rounds += 1
        messages.append({"role": "assistant", "content": response.content})

        tool_results = []
        for b in response.content:
            if b.type == "tool_use" and b.name == "search_pubmed":
                all_tool_calls.append(b.input)
                result = date_capped_pubmed_search(**b.input)
                tool_results.append({
                    "type": "tool_result", "tool_use_id": b.id, "content": result[:8000]
                })
        messages.append({"role": "user", "content": tool_results})

        response = client.messages.create(
            model=MODEL, max_tokens=16000, tools=[PUBMED_TOOL_SCHEMA],
            thinking={"type": "adaptive", "display": "summarized"},
            output_config={"effort": "high"}, messages=messages,
        )
        all_thinking.append("".join(b.thinking for b in response.content if b.type == "thinking"))

    if rounds == MAX_TOOL_ROUNDS and response.stop_reason == "tool_use":
        print(f"[WARNING] {persona_name} hit the {MAX_TOOL_ROUNDS}-round safety cap, "
              f"still requesting tools. This is a real finding worth noting, not just a limit to raise.")

    text = "".join(b.text for b in response.content if b.type == "text")
    return text, "\n---\n".join(all_thinking), response.stop_reason, all_tool_calls, rounds

In [45]:
week4_outputs = {}
for persona_name, success_criterion in PERSONAS.items():
    try:
        text, thinking, stop_reason, tool_calls, rounds = run_week4_persona(persona_name, success_criterion)
        print(f"{persona_name}: stop_reason={stop_reason}, rounds={rounds}, "
              f"tool_calls={tool_calls}, text={len(text)} chars")
        week4_outputs[persona_name] = text
        with open(f"week4_{persona_name}_run4.txt", "w", encoding="utf-8") as f:
            f.write(text)
        with open(f"week4_{persona_name}_run4_thinking.txt", "w", encoding="utf-8") as f:
            f.write(thinking)
    except Exception as e:
        print(f"{persona_name}: FAILED — {e}")
    time.sleep(1.0)

biology: stop_reason=end_turn, rounds=1, tool_calls=[{'query_term': 'TRANSEURO fetal ventral mesencephalic tissue dissection serotonin dopamine ratio graft-induced dyskinesia', 'max_results': 6}, {'query_term': 'graft-induced dyskinesia mechanism unresolved rostral caudal putamen serotonin', 'max_results': 6}], text=6019 chars
clinical: stop_reason=end_turn, rounds=1, tool_calls=[{'query_term': 'TRANSEURO trial protocol fetal cell transplantation Parkinson patient selection criteria', 'max_results': 5}, {'query_term': 'graft-induced dyskinesia clinical predictors Parkinson fetal transplant patient selection age severity', 'max_results': 5}], text=5422 chars
regulatory: stop_reason=end_turn, rounds=1, tool_calls=[{'query_term': 'TRANSEURO trial design fetal ventral mesencephalic transplantation Parkinson', 'max_results': 5}, {'query_term': 'fetal tissue transplantation Parkinson disease patient selection graft-induced dyskinesia prevention protocol', 'max_results': 5}], text=6273 chars
cmc_manufacturing: stop_reason=end_turn, rounds=2, tool_calls=[{'query_term': 'TRANSEURO fetal ventral mesencephalon tissue preparation protocol', 'max_results': 5}, {'query_term': 'human fetal tissue procurement standardization neural transplantation Parkinson', 'max_results': 5}, {'query_term': 'number of donor embryos required fetal mesencephalic graft Parkinson dopamine neuron survival', 'max_results': 5}, {'query_term': 'gestational age fetal ventral mesencephalon dopamine neuron yield transplantation', 'max_results': 5}], text=5119 chars